/*
 * TTTech ieee8021MstpMib-mib-module
 * Copyright(c) 2019 TTTech Industrial Automation AG.
 *
 * ALL RIGHTS RESERVED.
 * Usage of this software, including source code, netlists, documentation,
 * is subject to restrictions and conditions of the applicable license
 * agreement with TTTech Industrial Automation AG or its affiliates.
 *
 * All trademarks used are the property of their respective owners.
 *
 * TTTech Industrial Automation AG and its affiliates do not assume any liability
 * arising out of the application or use of any product described or shown
 * herein. TTTech Industrial Automation AG and its affiliates reserve the right to
 * make changes, at any time, in order to improve reliability, function or
 * design.
 *
 * Contact Information:
 * support@tttech-industrial.com
 * TTTech Industrial Automation AG, Schoenbrunnerstrasse 7, 1040 Vienna, Austria
 */
/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include "ieee8021MstpPortTable.h"
/* libbase includes */
#include "base_prints.h"
#include "base_defines.h"
#include "base_private_translators.h"
#include "base_linux_tool_helpers.h"
#include "base_mstp_linux_tools.h"

static char port_state_map[6][2][MAX_STR_LEN] = {//5 pairs
		{BASE_DISABLED_STR,   	BASE_ONE_STR},
		{BASE_LISTENING_STR, 	BASE_TWO_STR},
		{BASE_LEARNING_STR,  	BASE_THREE_STR},
		{BASE_FORWARDING_STR, 	BASE_FOUR_STR},
		{BASE_BLOCKING_STR,   	BASE_FIVE_STR},
		{BASE_DISCARDING_STR,   BASE_SIX_STR}
};

extern char truth_value_map[2][2][MAX_STR_LEN];

extern char port_role_map[4][2][MAX_STR_LEN];

extern u_long component_id; //component id is 1 - only one bridge is supported

/** Initializes the ieee8021MstpPortTable module */
void init_ieee8021MstpPortTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_ieee8021MstpPortTable();
}

/** Initialize the ieee8021MstpPortTable table by defining its contents and how it's structured */
void initialize_table_ieee8021MstpPortTable(void)
{
    const oid ieee8021MstpPortTable_oid[] = {1,3,111,2,802,1,1,6,1,4};
    const size_t ieee8021MstpPortTable_oid_len   = OID_LENGTH(ieee8021MstpPortTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_tdata                   *table_data;
    netsnmp_table_registration_info *table_info;
    netsnmp_cache                   *cache;

    DEBUGMSGTL(("ieee8021MstpPortTable:init", "initializing table ieee8021MstpPortTable\n"));

    reg = netsnmp_create_handler_registration(
              "ieee8021MstpPortTable",     ieee8021MstpPortTable_handler,
              ieee8021MstpPortTable_oid, ieee8021MstpPortTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_data = netsnmp_tdata_create_table( "ieee8021MstpPortTable", 0 );
    if (NULL == table_data) {
        snmp_log(LOG_ERR,"error creating tdata table for ieee8021MstpPortTable\n");
        return;
    }
    cache = netsnmp_cache_create(IEEE8021MSTPPORTTABLE_TIMEOUT,
                                  ieee8021MstpPortTable_load, ieee8021MstpPortTable_free,
                                  ieee8021MstpPortTable_oid, ieee8021MstpPortTable_oid_len);
    if (NULL == cache) {
        snmp_log(LOG_ERR,"error creating cache for ieee8021MstpPortTable\n");
    }
    else
    {
        cache->magic = (void *)table_data;
		cache->flags =  NETSNMP_CACHE_DONT_FREE_EXPIRED     | \
						NETSNMP_CACHE_DONT_AUTO_RELEASE     | \
						NETSNMP_CACHE_AUTO_RELOAD           | \
						NETSNMP_CACHE_DONT_FREE_BEFORE_LOAD | \
						NETSNMP_CACHE_DONT_INVALIDATE_ON_SET ;
	}
    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    if (NULL == table_info) {
        snmp_log(LOG_ERR,"error creating table info for ieee8021MstpPortTable\n");
        return;
    }
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_UNSIGNED,  /* index: ieee8021MstpPortComponentId */
                           ASN_UNSIGNED,  /* index: ieee8021MstpPortMstId */
                           ASN_UNSIGNED,  /* index: ieee8021MstpPortNum */
                           0);

    table_info->min_column = COLUMN_IEEE8021MSTPPORTUPTIME;
    table_info->max_column = COLUMN_IEEE8021MSTPPORTADMINPATHCOST;
    
    netsnmp_tdata_register( reg, table_data, table_info );

    /* Initialise the contents of the table here */
    if(0 != init_ieee8021MstpPortTable_with_sys_data(table_data))
    {
        snmp_log(LOG_ERR,"ERROR: %s(): Table Init was unsuccessful.\n", __func__);
        free(table_info);
        return;
    }
    else
    {
        snmp_log(LOG_INFO,"INFO: %s(): Table Init was successful.\n", __func__);
        netsnmp_cache_timer_start(cache);
    }
}

/* init table */
int init_ieee8021MstpPortTable_with_sys_data(netsnmp_tdata *table_data)
{
    netsnmp_tdata_row *row = NULL;
    char ports_name[MAX_NUM_OF_INTERFACES][MAX_STR_LEN] = {0};
    char bridges_name[MAX_NUM_OF_INTERFACES][MAX_STR_LEN] = {0};
    char mstp_ids[BASE_MAX_VID][BASE_TEN] = {0};
    char tmp_port_id[BASE_MAX_VID][BASE_TEN] = {0};
    int i = 0, j = 0;

    /* gather fresh system data */
    if(EXIT_FAILURE == get_mstp_bridge_names(bridges_name, MAX_NUM_OF_INTERFACES, MAX_STR_LEN))
    {
    	snmp_log(LOG_ERR, SNMP_MSG_FUN_AND_MSG, __func__, "get_mstp_bridges_name is failed");
        return 1;
    }
	if (EXIT_FAILURE == get_bridge_mstpi(mstp_ids, BASE_MAX_VID, BASE_TEN, bridges_name[0]))// only one bridge
	{
    	snmp_log(LOG_ERR, SNMP_MSG_FUN_AND_MSG, __func__, "mstp ids are unreachable");
        return 1;
	}
    if(EXIT_FAILURE == get_mstp_bridge_port_names(ports_name, MAX_NUM_OF_INTERFACES, MAX_STR_LEN, bridges_name[0]))
    {
    	snmp_log(LOG_ERR, SNMP_MSG_FUN_AND_MSG, __func__, "ports' name are unreachable");
        return 1;
    }

	while((i < BASE_MAX_VID) && (0 != strncmp("", mstp_ids[i], BASE_TEN)))
	{
		j = 0;
		while((j < MAX_NUM_OF_INTERFACES) && (0 != strncmp(ports_name[j], "", MAX_STR_LEN)))
		{
		    if(EXIT_FAILURE == get_mstp_port_id(tmp_port_id, BASE_MAX_VID, BASE_TEN, bridges_name[0], ports_name[j]))
		    {
		    	snmp_log(LOG_ERR, SNMP_MSG_FUN_XML_EL_AND_MSG, __func__, "port's id is unreachable for port's name (%s)", ports_name[j]);
		        return 1;/* error */
		    }
			row = ieee8021MstpPortTable_createEntry(table_data, component_id,
					strtoul(mstp_ids[i], NULL, 10), strtoul(tmp_port_id[0], NULL, 10));
			if(NULL != row)
			{
				ieee8021MstpPortTable_fillEntry(ports_name[j], bridges_name[0], mstp_ids[i], (ieee8021MstpPortTable_entry_t*)row->data);
			}
			else
			{
				snmp_log(LOG_ERR, "%s(): New row is not created.\n", __func__);
				return 1;/* error */
			}
			row = NULL;
			j++;
		}
		i++;
	}

    return 0;/* success */
}

/* create a new row in the table */
netsnmp_tdata_row* ieee8021MstpPortTable_createEntry( netsnmp_tdata *table_data
                                                    , u_long  ieee8021MstpPortComponentId
                                                    , u_long  ieee8021MstpPortMstId
                                                    , u_long  ieee8021MstpPortNum)
{
    struct ieee8021MstpPortTable_entry *entry;
    netsnmp_tdata_row *row;

    entry = SNMP_MALLOC_TYPEDEF(struct ieee8021MstpPortTable_entry);
    if (!entry)
        return NULL;

    row = netsnmp_tdata_create_row();
    if (!row) {
        SNMP_FREE(entry);
        return NULL;
    }
    row->data = entry;

    snmp_log(LOG_INFO,"ieee8021MstpPortTable_createEntry - (%ld) - (%ld) -(%ld)\n",
    		ieee8021MstpPortComponentId, ieee8021MstpPortMstId, ieee8021MstpPortNum);

    entry->ieee8021MstpPortComponentId = ieee8021MstpPortComponentId;
    netsnmp_tdata_row_add_index( row, ASN_UNSIGNED,
                                 &(entry->ieee8021MstpPortComponentId),
                                 sizeof(entry->ieee8021MstpPortComponentId));
    entry->ieee8021MstpPortMstId = ieee8021MstpPortMstId;
    netsnmp_tdata_row_add_index( row, ASN_UNSIGNED,
                                 &(entry->ieee8021MstpPortMstId),
                                 sizeof(entry->ieee8021MstpPortMstId));
    entry->ieee8021MstpPortNum = ieee8021MstpPortNum;
    netsnmp_tdata_row_add_index( row, ASN_UNSIGNED,
                                 &(entry->ieee8021MstpPortNum),
                                 sizeof(entry->ieee8021MstpPortNum));
    if (table_data)
        netsnmp_tdata_add_row( table_data, row );
    return row;
}

/* fill a new row data in the table */
int ieee8021MstpPortTable_fillEntry(char port_name[MAX_STR_LEN],
		char bridge_name[MAX_STR_LEN], char mstp_id[BASE_FIVE], ieee8021MstpPortTable_entry_t* entry)
{
    char result_array[MAX_NUM_OF_INTERFACES][MAX_STR_LEN];
    int ret = 0;//OK

    do{
		if (!entry)
		{
			snmp_log(LOG_ERR, SNMP_MSG_FUN_AND_MSG, __func__, "entry == NULL");
			ret = 1;/* error */
			break;
		}
		/* list ieee8021MstpPortEntry, leaf ieee8021MstpPortState */
		if(EXIT_SUCCESS == get_mstp_port_state(result_array, MAX_NUM_OF_INTERFACES, MAX_STR_LEN, bridge_name, port_name, mstp_id))
		{
			if(EXIT_FAILURE == translate_single_string_using_map(result_array[0], port_state_map))
			{
				snmp_log(LOG_ERR, SNMP_MSG_FUN_AND_MSG, __func__, "Failed to translate port state value!");
				ret = 1;/* error */
				break;
			}
			entry->ieee8021MstpPortState = strtol(result_array[0], NULL, 10);
		}
		else
		{
			ret = 1;/* error */
			break;
		}
		/* list ieee8021MstpPortEntry, leaf ieee8021MstpPortPriority */
		if(EXIT_SUCCESS == get_mstp_port_prioriy(result_array, MAX_NUM_OF_INTERFACES, MAX_STR_LEN, bridge_name, port_name, mstp_id))
		{
			entry->ieee8021MstpPortPriority = strtol(result_array[0], NULL, 10);
		}
		else
		{
			ret = 1;/* error */
			break;
		}
		/* list ieee8021MstpPortEntry, leaf ieee8021MstpPortPathCost */
		if(EXIT_SUCCESS == get_mstp_port_path_cost(result_array, MAX_NUM_OF_INTERFACES, MAX_STR_LEN, bridge_name, port_name, mstp_id))
		{
			entry->ieee8021MstpPortPathCost = strtol(result_array[0], NULL, 10);
		}
		else
		{
			ret = 1;/* error */
			break;
		}
		/* list ieee8021MstpPortEntry, leaf ieee8021MstpPortDesignatedRoot */
		if(EXIT_SUCCESS == get_mstp_port_dsgn_root(result_array, MAX_NUM_OF_INTERFACES, MAX_STR_LEN, bridge_name, port_name, mstp_id))
		{
			strncpy(entry->ieee8021MstpPortDesignatedRoot, result_array[0], MAX_STR_LEN);
			entry->ieee8021MstpPortDesignatedRoot_len = strlen(entry->ieee8021MstpPortDesignatedRoot);
		}
		else
		{
			ret = 1;/* error */
			break;
		}
		/* list ieee8021MstpPortEntry, leaf ieee8021MstpPortDesignatedCost */
		if(EXIT_SUCCESS == get_mstp_port_dsgn_cost(result_array, MAX_NUM_OF_INTERFACES, MAX_STR_LEN, bridge_name, port_name, mstp_id))
		{
			entry->ieee8021MstpPortDesignatedCost = strtol(result_array[0], NULL, 10);
		}
		else
		{
			ret = 1;/* error */
			break;
		}
		/* list ieee8021MstpPortEntry, leaf ieee8021MstpPortDesignatedBridge */
		if(EXIT_SUCCESS == get_mstp_port_dsgn_bridge(result_array, MAX_NUM_OF_INTERFACES, MAX_STR_LEN, bridge_name, port_name, mstp_id))
		{
			strncpy(entry->ieee8021MstpPortDesignatedBridge, result_array[0], MAX_STR_LEN);
			entry->ieee8021MstpPortDesignatedBridge_len = strlen(entry->ieee8021MstpPortDesignatedBridge);
		}
		else
		{
			ret = 1;/* error */
			break;
		}
		/* list ieee8021MstpPortEntry, leaf ieee8021MstpPortDesignatedPort */
		if(EXIT_SUCCESS == get_mstp_port_dsgn_port(result_array, MAX_NUM_OF_INTERFACES, MAX_STR_LEN, bridge_name, port_name, mstp_id))
		{
			entry->ieee8021MstpPortDesignatedPort = strtoul(result_array[0], NULL, 10);
		}
		else
		{
			ret = 1;/* error */
			break;
		}
		/* list ieee8021MstpPortEntry, leaf ieee8021MstpPortRole */
		if(EXIT_SUCCESS == get_mstp_port_role(result_array, MAX_NUM_OF_INTERFACES, MAX_STR_LEN, bridge_name, port_name, mstp_id))
		{
			if(EXIT_FAILURE == translate_single_string_using_map(result_array[0], port_role_map))
			{
				snmp_log(LOG_ERR, SNMP_MSG_FUN_AND_MSG, __func__, "Failed to translate port role value!");
				ret = 1;/* error */
				break;
			}
			entry->ieee8021MstpPortRole = strtol(result_array[0], NULL, 10);
		}
		else
		{
			ret = 1;/* error */
			break;
		}
		/* list ieee8021MstpPortEntry, leaf ieee8021MstpPortDisputed */
		if(EXIT_SUCCESS == get_mstp_port_disputed(result_array, MAX_NUM_OF_INTERFACES, MAX_STR_LEN, bridge_name, port_name, mstp_id))
		{
			if(EXIT_FAILURE == translate_single_string_using_map(result_array[0], truth_value_map))
			{
				snmp_log(LOG_ERR, SNMP_MSG_FUN_AND_MSG, __func__, "Failed to translate port disputed value!");
				ret = 1;/* error */
				break;
			}
			entry->ieee8021MstpPortDisputed = strtol(result_array[0], NULL, 10);
		}
		else
		{
			ret = 1;/* error */
			break;
		}
    }while(0);

    return ret;
}

/* remove a row from the table */
void ieee8021MstpPortTable_removeEntry(netsnmp_tdata* table_data, netsnmp_tdata_row* row)
{
    struct ieee8021MstpPortTable_entry *entry;

    if (!row) return;/* Nothing to remove */

    snmp_log(LOG_INFO, "ieee8021MstpPortTable_removeEntry entry.\n");

    entry = (struct ieee8021MstpPortTable_entry *)row->data;
    SNMP_FREE( entry );   /* XXX - release any other internal resources */

    if (table_data)
        netsnmp_tdata_remove_and_delete_row( table_data, row );
    else
        netsnmp_tdata_delete_row( row );    
}

/* Example cache handling - set up table_data list from a suitable file */
int ieee8021MstpPortTable_load( netsnmp_cache *cache, void *vmagic )
{
    /* will be used to iterate trough ieee8021BridgeBaseTable_head */
	netsnmp_tdata_row* agent_row = NULL;
	/* helper to keep next agent row */
	netsnmp_tdata_row* next_agent_row = NULL;
	/* will be used to check existence of the bridge */
	netsnmp_tdata* table = (netsnmp_tdata *)vmagic;
	ieee8021MstpPortTable_entry_t* entry = NULL;
	int port_found = 0;
	char ports_name[MAX_NUM_OF_INTERFACES][MAX_STR_LEN] = {0};
	char bridges_name[MAX_NUM_OF_INTERFACES][MAX_STR_LEN] = {0};
	char mstp_ids[BASE_MAX_VID][BASE_TEN] = {0};
	char tmp_port_id[BASE_MAX_VID][BASE_TEN] = {0};
	int i = 0, j = 0;

	/* gather fresh system data */
	if(EXIT_FAILURE == get_mstp_bridge_names(bridges_name, MAX_NUM_OF_INTERFACES, MAX_STR_LEN))
	{
		snmp_log(LOG_ERR, SNMP_MSG_FUN_AND_MSG, __func__, "get_mstp_bridges_name failed");
		return 1;
	}
	if (EXIT_FAILURE == get_bridge_mstpi(mstp_ids, BASE_MAX_VID, BASE_TEN, bridges_name[0]))// only one bridge
	{
		snmp_log(LOG_ERR, SNMP_MSG_FUN_AND_MSG, __func__, "get_bridge_mstpi is failed");
		return 1;
	}
	if(EXIT_FAILURE == get_mstp_bridge_port_names(ports_name, MAX_NUM_OF_INTERFACES, MAX_STR_LEN, bridges_name[0]))//only one bridge is supported
	{
		snmp_log(LOG_ERR, SNMP_MSG_FUN_AND_MSG, __func__, "get_mstp_bridge_ports_name is failed");
		return 1;
	}

	/* returns the first row in the table */
	agent_row = netsnmp_tdata_row_first (table);

	while(NULL != agent_row)
	{
		entry = (ieee8021MstpPortTable_entry_t*)agent_row->data;

		if(NULL != entry)
		{
			/* there is no more agent_row, erase it from agent */
			if(!entry->ieee8021MstpPortComponentId || !entry->ieee8021MstpPortMstId || !entry->ieee8021MstpPortNum)
			{
				snmp_log(LOG_DEBUG, SNMP_MSG_FUN_AND_MSG, __func__,
						"there is no more agent_row, erase it from agent");
				/* returns next row */
				next_agent_row = netsnmp_tdata_row_next (table, agent_row);
				ieee8021MstpPortTable_removeEntry(table, agent_row);
				agent_row = next_agent_row;
				next_agent_row = NULL;
			}
			/* agent_row exist on system, skip it (leave it on agent) - just update values */
			else
			{
				i = 0;
				while((i < BASE_MAX_VID) && (0 != strncmp("", mstp_ids[i], BASE_TEN)))
				{
					if( (component_id == entry->ieee8021MstpPortComponentId)
					 && (strtoul(mstp_ids[i], NULL, 10) == entry->ieee8021MstpPortMstId))
					{
						j = 0;
						while((j < MAX_NUM_OF_INTERFACES) && (0 != strncmp(ports_name[j], "", MAX_STR_LEN)))
						{
							if(EXIT_FAILURE == get_mstp_port_id(tmp_port_id, BASE_MAX_VID, BASE_TEN, bridges_name[0], ports_name[j]))
							{
								snmp_log(LOG_ERR, SNMP_MSG_FUN_XML_EL_AND_MSG, __func__, "port's id is unreachable for port's name (%s)", ports_name[j]);
								return 1;/* error */
							}
							if(strtoul(tmp_port_id[0], NULL, 10) == entry->ieee8021MstpPortNum)
							{
								/* refresh data in this existing row on agent */
								ieee8021MstpPortTable_fillEntry(ports_name[j], bridges_name[0], mstp_ids[i], (ieee8021MstpPortTable_entry_t*)agent_row->data);
							}
							j++;
						}
					}
					i++;
				}
				/* take next */
				agent_row = netsnmp_tdata_row_next (table, agent_row);
			}
		}
		else
		{
			snmp_log(LOG_ERR, SNMP_MSG_FUN_AND_MSG, __func__, "agent_row->data is NULL");
		}
	}
	i = 0;
	while((i < BASE_MAX_VID) && (0 != strncmp("", mstp_ids[i], BASE_TEN)))
	{
		j = 0;
		while((j < MAX_NUM_OF_INTERFACES) && (0 != strncmp(ports_name[j], "", MAX_STR_LEN)))
		{
		    if(EXIT_FAILURE == get_mstp_port_id(tmp_port_id, BASE_MAX_VID, BASE_TEN, bridges_name[0], ports_name[j]))
		    {
		    	snmp_log(LOG_ERR, SNMP_MSG_FUN_XML_EL_AND_MSG, __func__, "port's id is unreachable for port's name", ports_name[j]);
		        return 1;/* error */
		    }
			/* returns the first row in the table */
			agent_row = netsnmp_tdata_row_first (table);
			while((NULL != agent_row) && (port_found == 0))
			{
				entry = (ieee8021MstpPortTable_entry_t*)agent_row->data;
				if(  (component_id == entry->ieee8021MstpPortComponentId)
				  && (strtoul(mstp_ids[i], NULL, 10) == entry->ieee8021MstpPortMstId)
				  && (strtoul(tmp_port_id[0], NULL, 10) == entry->ieee8021MstpPortNum)//port
				  )
				{
					port_found = 1;
				}
				agent_row = netsnmp_tdata_row_next (table, agent_row);
			}

			if(port_found == 0)
			{
				agent_row = ieee8021MstpPortTable_createEntry(table, component_id, strtoul(mstp_ids[i], NULL, 10), strtoul(tmp_port_id[0], NULL, 10));
				ieee8021MstpPortTable_fillEntry(ports_name[j], bridges_name[0], mstp_ids[i], agent_row->data);
			}
			j++;
			port_found = 0;
		}
		i++;
	}
    return 0;  /* OK */
}

void
ieee8021MstpPortTable_free( netsnmp_cache *cache, void *vmagic ) {
    netsnmp_tdata     *table = (netsnmp_tdata *)vmagic;
    netsnmp_tdata_row *this;

    while ((this = netsnmp_tdata_row_first(table))) {
        netsnmp_tdata_remove_and_delete_row(table, this);
    }
}

/** handles requests for the ieee8021MstpPortTable table */
int
ieee8021MstpPortTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    netsnmp_tdata              *table_data;
    netsnmp_tdata_row          *table_row;
    ieee8021MstpPortTable_entry_t* table_entry;
    int                         ret;
    char tmp_object_value[MAX_STR_LEN] = {0};
    char tmp_component_id[MAX_STR_LEN] = {0};
    char tmp_mstp_id[MAX_STR_LEN]      = {0};
    char tmp_port_num[MAX_STR_LEN]     = {0};

    DEBUGMSGTL(("ieee8021MstpPortTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            if (request->processed)
                continue;

            table_entry = (struct ieee8021MstpPortTable_entry *)
                              netsnmp_tdata_extract_entry(request);
            table_info  =     netsnmp_extract_table_info( request);
    
            switch (table_info->colnum) {
#if 0
            case COLUMN_IEEE8021MSTPPORTUPTIME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_TIMETICKS,
                                            table_entry->ieee8021MstpPortUptime);
                break;
#endif
            case COLUMN_IEEE8021MSTPPORTSTATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ieee8021MstpPortState);
                break;
            case COLUMN_IEEE8021MSTPPORTPRIORITY:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ieee8021MstpPortPriority);
                break;
            case COLUMN_IEEE8021MSTPPORTPATHCOST:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ieee8021MstpPortPathCost);
                break;
            case COLUMN_IEEE8021MSTPPORTDESIGNATEDROOT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->ieee8021MstpPortDesignatedRoot,
                                          table_entry->ieee8021MstpPortDesignatedRoot_len);
                break;
            case COLUMN_IEEE8021MSTPPORTDESIGNATEDCOST:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ieee8021MstpPortDesignatedCost);
                break;
            case COLUMN_IEEE8021MSTPPORTDESIGNATEDBRIDGE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->ieee8021MstpPortDesignatedBridge,
                                          table_entry->ieee8021MstpPortDesignatedBridge_len);
                break;
            case COLUMN_IEEE8021MSTPPORTDESIGNATEDPORT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->ieee8021MstpPortDesignatedPort);
                break;
            case COLUMN_IEEE8021MSTPPORTROLE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ieee8021MstpPortRole);
                break;
            case COLUMN_IEEE8021MSTPPORTDISPUTED:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ieee8021MstpPortDisputed);
                break;
#if 0
            case COLUMN_IEEE8021MSTPPORTADMINPATHCOST:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ieee8021MstpPortAdminPathCost);
                break;
#endif
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            if (request->processed)
                continue;
#if 0
            table_entry = (struct ieee8021MstpPortTable_entry *)
                              netsnmp_tdata_extract_entry(request);
#endif
            table_info  =     netsnmp_extract_table_info( request);
    
            switch (table_info->colnum) {
            case COLUMN_IEEE8021MSTPPORTPRIORITY:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_IEEE8021MSTPPORTPATHCOST:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
#if 0
            case COLUMN_IEEE8021MSTPPORTADMINPATHCOST:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
#endif
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            if (request->processed)
                continue;

            table_entry = (struct ieee8021MstpPortTable_entry *)
                              netsnmp_tdata_extract_entry(request);
            table_info  =     netsnmp_extract_table_info( request);
    
            switch (table_info->colnum) {
            case COLUMN_IEEE8021MSTPPORTPRIORITY:
                table_entry->old_ieee8021MstpPortPriority = table_entry->ieee8021MstpPortPriority;
                table_entry->ieee8021MstpPortPriority     = *request->requestvb->val.integer;
	            snprintf(tmp_object_value, MAX_STR_LEN, "%ld", table_entry->ieee8021MstpPortPriority);
	            snprintf(tmp_component_id, MAX_STR_LEN, "%lu", table_entry->ieee8021MstpPortComponentId);
	            snprintf(tmp_mstp_id, MAX_STR_LEN, "%lu", table_entry->ieee8021MstpPortMstId);
	            snprintf(tmp_port_num, MAX_STR_LEN, "%lu", table_entry->ieee8021MstpPortNum);
				if(EXIT_FAILURE == set_mstp_port_priority(tmp_component_id, tmp_port_num, tmp_mstp_id, tmp_object_value))
				{
					netsnmp_set_request_error(reqinfo, request, SNMP_ERR_WRONGVALUE);
	                snmp_log(LOG_DEBUG, SNMP_MSG_FUN_AND_MSG, __func__,
	                		"ieee8021MstpPortPriority MODE_SET_ACTION failed");
					return SNMP_ERR_NOERROR;
				}
                break;
            case COLUMN_IEEE8021MSTPPORTPATHCOST:
                table_entry->old_ieee8021MstpPortPathCost = table_entry->ieee8021MstpPortPathCost;
                table_entry->ieee8021MstpPortPathCost     = *request->requestvb->val.integer;
	            snprintf(tmp_object_value, MAX_STR_LEN, "%ld", table_entry->ieee8021MstpPortPathCost);
	            snprintf(tmp_component_id, MAX_STR_LEN, "%lu", table_entry->ieee8021MstpPortComponentId);
	            snprintf(tmp_mstp_id, MAX_STR_LEN, "%lu", table_entry->ieee8021MstpPortMstId);
	            snprintf(tmp_port_num, MAX_STR_LEN, "%lu", table_entry->ieee8021MstpPortNum);
				if(EXIT_FAILURE == set_mstp_port_path_cost(tmp_component_id, tmp_port_num, tmp_mstp_id, tmp_object_value))
				{
					netsnmp_set_request_error(reqinfo, request, SNMP_ERR_WRONGVALUE);
	                snmp_log(LOG_DEBUG, SNMP_MSG_FUN_AND_MSG, __func__,
	                		"ieee8021MstpPortPathCost MODE_SET_ACTION failed");
					return SNMP_ERR_NOERROR;
				}
                break;
#if 0
            case COLUMN_IEEE8021MSTPPORTADMINPATHCOST:
                table_entry->old_ieee8021MstpPortAdminPathCost = table_entry->ieee8021MstpPortAdminPathCost;
                table_entry->ieee8021MstpPortAdminPathCost     = *request->requestvb->val.integer;
                break;
#endif
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            if (request->processed)
                continue;

            table_entry = (struct ieee8021MstpPortTable_entry *)
                              netsnmp_tdata_extract_entry(request);
#if 0
            table_row   =     netsnmp_tdata_extract_row(  request);
            table_data  =     netsnmp_tdata_extract_table(request);
#endif
            table_info  =     netsnmp_extract_table_info( request);
    
            switch (table_info->colnum) {
            case COLUMN_IEEE8021MSTPPORTPRIORITY:
                table_entry->ieee8021MstpPortPriority     = table_entry->old_ieee8021MstpPortPriority;
                table_entry->old_ieee8021MstpPortPriority = 0;
                break;
            case COLUMN_IEEE8021MSTPPORTPATHCOST:
                table_entry->ieee8021MstpPortPathCost     = table_entry->old_ieee8021MstpPortPathCost;
                table_entry->old_ieee8021MstpPortPathCost = 0;
                break;
#if 0
            case COLUMN_IEEE8021MSTPPORTADMINPATHCOST:
                table_entry->ieee8021MstpPortAdminPathCost     = table_entry->old_ieee8021MstpPortAdminPathCost;
                table_entry->old_ieee8021MstpPortAdminPathCost = 0;
                break;
#endif
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
