/*
 * TTTech ieee8021BridgeMib-mib-module
 * Copyright(c) 2019 TTTech Industrial Automation AG.
 *
 * ALL RIGHTS RESERVED.
 * Usage of this software, including source code, netlists, documentation,
 * is subject to restrictions and conditions of the applicable license
 * agreement with TTTech Industrial Automation AG or its affiliates.
 *
 * All trademarks used are the property of their respective owners.
 *
 * TTTech Industrial Automation AG and its affiliates do not assume any liability
 * arising out of the application or use of any product described or shown
 * herein. TTTech Industrial Automation AG and its affiliates reserve the right to
 * make changes, at any time, in order to improve reliability, function or
 * design.
 *
 * Contact Information:
 * support@tttech-industrial.com
 * TTTech Industrial Automation AG, Schoenbrunnerstrasse 7, 1040 Vienna, Austria
 */
/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef IEEE8021BRIDGETRAFFICCLASSTABLE_H
#define IEEE8021BRIDGETRAFFICCLASSTABLE_H

#include "base_prints.h"

typedef struct ieee8021BridgeTrafficClassTable_entry ieee8021BridgeTrafficClassTable_entry_t;

/* function declarations */
void init_ieee8021BridgeTrafficClassTable(void);
void initialize_table_ieee8021BridgeTrafficClassTable(void);
int init_ieee8021BridgeTrafficClassTable_with_sys_data(netsnmp_tdata *table_data);
netsnmp_tdata_row* ieee8021BridgeTrafficClassTable_createEntry(
		netsnmp_tdata *table_data,
		u_long ieee8021BridgeBasePortComponentId,
		u_long ieee8021BridgeBasePort,
		u_long ieee8021BridgeTrafficClassPriority);
int ieee8021BridgeTrafficClassTable_fillEntry(char port_name[MAX_STR_LEN], unsigned int priority,
		ieee8021BridgeTrafficClassTable_entry_t *entry);
Netsnmp_Node_Handler ieee8021BridgeTrafficClassTable_handler;
NetsnmpCacheLoad ieee8021BridgeTrafficClassTable_load;
NetsnmpCacheFree ieee8021BridgeTrafficClassTable_free;
#define IEEE8021BRIDGETRAFFICCLASSTABLE_TIMEOUT  60

/* column number definitions for table ieee8021BridgeTrafficClassTable */
#define COLUMN_IEEE8021BRIDGETRAFFICCLASSPRIORITY		1
#define COLUMN_IEEE8021BRIDGETRAFFICCLASS				2

/* Typical data structure for a row entry */
struct ieee8021BridgeTrafficClassTable_entry {
	/* Index values */
	u_long ieee8021BridgeBasePortComponentId;
	u_long ieee8021BridgeBasePort;
	u_long ieee8021BridgeTrafficClassPriority;

	/* Column values */
	long ieee8021BridgeTrafficClass;
	long old_ieee8021BridgeTrafficClass;

	int   valid;
};

#endif /* IEEE8021BRIDGETRAFFICCLASSTABLE_H */
