/*
 * TTTech ieee8021MstpMib-mib-module
 * Copyright(c) 2019 TTTech Computertechnik AG.
 *
 * ALL RIGHTS RESERVED.
 * Usage of this software, including source code, netlists, documentation,
 * is subject to restrictions and conditions of the applicable license
 * agreement with TTTech Computertechnik AG or its affiliates.
 *
 * All trademarks used are the property of their respective owners.
 *
 * TTTech Computertechnik AG and its affiliates do not assume any liability
 * arising out of the application or use of any product described or shown
 * herein. TTTech Computertechnik AG and its affiliates reserve the right to
 * make changes, at any time, in order to improve reliability, function or
 * design.
 *
 * Contact Information:
 * support@4me.tttech-dependablenetworks.com
 * TTTech Computertechnik AG, Schoenbrunnerstrasse 7, 1040 Vienna, Austria
 */
/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include "ieee8021MstpCistTable.h"
/* libbase includes */
#include "base_prints.h"
#include "base_mstp_linux_tools.h"
#include "base_private_translators.h"

/* map for TruthValue defined in the SNMPv2-TC MIB module */
char truth_value_map[2][2][MAX_STR_LEN] = {//2 pairs
		{BASE_YES, BASE_ONE_STR},
		{BASE_NO,  BASE_TWO_STR},
};

/* global variable */
extern u_long component_id;// only one bridge is supported, hard coded

/** Initializes the ieee8021MstpCistTable module */
void init_ieee8021MstpCistTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_ieee8021MstpCistTable();
}

/** Initialize the ieee8021MstpCistTable table by defining its contents and how it's structured */
void
initialize_table_ieee8021MstpCistTable(void)
{
    const oid ieee8021MstpCistTable_oid[] = {1,3,111,2,802,1,1,6,1,1};
    const size_t ieee8021MstpCistTable_oid_len   = OID_LENGTH(ieee8021MstpCistTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_tdata                   *table_data;
    netsnmp_table_registration_info *table_info;
    netsnmp_cache                   *cache;

    DEBUGMSGTL(("ieee8021MstpCistTable:init", "initializing table ieee8021MstpCistTable\n"));

    reg = netsnmp_create_handler_registration(
              "ieee8021MstpCistTable",     ieee8021MstpCistTable_handler,
              ieee8021MstpCistTable_oid, ieee8021MstpCistTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_data = netsnmp_tdata_create_table( "ieee8021MstpCistTable", 0 );
    if (NULL == table_data) {
        snmp_log(LOG_ERR,"error creating tdata table for ieee8021MstpCistTable\n");
        return;
    }
    cache = netsnmp_cache_create(IEEE8021MSTPCISTTABLE_TIMEOUT,
                                  ieee8021MstpCistTable_load, ieee8021MstpCistTable_free,
                                  ieee8021MstpCistTable_oid, ieee8021MstpCistTable_oid_len);
    if (NULL == cache) {
        snmp_log(LOG_ERR,"error creating cache for ieee8021MstpCistTable\n");
    }
    else
    {
        cache->magic = (void *)table_data;
        cache->flags =  NETSNMP_CACHE_DONT_FREE_EXPIRED     | \
                        NETSNMP_CACHE_DONT_AUTO_RELEASE     | \
                        NETSNMP_CACHE_AUTO_RELOAD           | \
                        NETSNMP_CACHE_DONT_FREE_BEFORE_LOAD | \
                        NETSNMP_CACHE_DONT_INVALIDATE_ON_SET ;
    }

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    if (NULL == table_info) {
        snmp_log(LOG_ERR,"error creating table info for ieee8021MstpCistTable\n");
        return;
    }
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_UNSIGNED,  /* index: ieee8021MstpCistComponentId */
                           0);

    table_info->min_column = COLUMN_IEEE8021MSTPCISTBRIDGEIDENTIFIER;
    table_info->max_column = COLUMN_IEEE8021MSTPCISTMAXHOPS;
    
    netsnmp_tdata_register( reg, table_data, table_info );

    /* Initialise the contents of the table here */
    if(0 != init_ieee8021MstpCistTable_with_sys_data(table_data))
    {
        snmp_log(LOG_ERR,"ERROR: %s(): Table Init was unsuccessful.\n", __func__);
        free(table_info);
        return;
    }
    else
    {
        snmp_log(LOG_INFO,"INFO: %s(): Table Init was successful.\n", __func__);
        netsnmp_cache_timer_start(cache);
    }
}

/* init table */
int init_ieee8021MstpCistTable_with_sys_data(netsnmp_tdata *table_data)
{
    netsnmp_tdata_row *row = NULL;
    int ret = 0;//success
    char bridges_name[MAX_NUM_OF_INTERFACES][MAX_STR_LEN] = {0};

    do{
		/* gather system data */
		if(EXIT_FAILURE == get_mstp_bridge_names(bridges_name, MAX_NUM_OF_INTERFACES, MAX_STR_LEN))
		{
			snmp_log(LOG_ERR, "ERROR: %s(): Internal error. Bridges' names are unreachable.\n", __func__);
			ret = 1;
			break;
		}
		// remove module from server if system supports more than one bridge
		if(0 != strncmp(bridges_name[1], "", MAX_STR_LEN))
		{
			snmp_log(LOG_ERR, "ERROR: %s(): Internal error. Bridges' names are unreachable.\n", __func__);
			ret = 1;
			break;
		}
		if(0 != strncmp(bridges_name[0], "", MAX_STR_LEN))
		{
			row = ieee8021MstpCistTable_createEntry(table_data, component_id);
			if(NULL != row)
			{
				if(0 != ieee8021MstpCistTable_fillEntry(bridges_name[0], (ieee8021MstpCistTable_entry_t*)row->data))
				{
					snmp_log(LOG_ERR, "ERROR: %s(): New row is not filled.\n", __func__);
					ret = 1;/* error */
					break;
				}
			}
			else
			{
				snmp_log(LOG_ERR, "ERROR: %s(): New row is not created.\n", __func__);
				ret = 1;/* error */
				break;
			}
		}
	}while(0);

    return ret;
}

/* create a new row in the table */
netsnmp_tdata_row* ieee8021MstpCistTable_createEntry(netsnmp_tdata *table_data, u_long  ieee8021MstpCistComponentId)
{
    struct ieee8021MstpCistTable_entry *entry;
    netsnmp_tdata_row *row;

    entry = SNMP_MALLOC_TYPEDEF(struct ieee8021MstpCistTable_entry);
    if (!entry)
        return NULL;

    row = netsnmp_tdata_create_row();
    if (!row) {
        SNMP_FREE(entry);
        return NULL;
    }
    row->data = entry;

    snmp_log(LOG_INFO,"ieee8021MstpCistTable_createEntry - (%ld)\n",
    		ieee8021MstpCistComponentId);

    entry->ieee8021MstpCistComponentId = ieee8021MstpCistComponentId;
    netsnmp_tdata_row_add_index( row, ASN_UNSIGNED,
                                 &(entry->ieee8021MstpCistComponentId),
                                 sizeof(entry->ieee8021MstpCistComponentId));
    if (table_data)
        netsnmp_tdata_add_row( table_data, row );
    return row;
}

/* fill a new row data in the table */
int ieee8021MstpCistTable_fillEntry(char bridge_name[MAX_STR_LEN],
		ieee8021MstpCistTable_entry_t *entry)
{
    char result_array[MAX_NUM_OF_INTERFACES][MAX_STR_LEN];
    int ret = 0; //success

    snmp_log(LOG_DEBUG, "%s(): is called.\n", __func__);

    do{
		if (!entry)
		{
			snmp_log(LOG_ERR, "%s(): entry == NULL\n", __func__);
			ret = 1;/* error */
			break;
		}

		/* list ieee8021MstpCistEntry, leaf ieee8021MstpCistBridgeIdentifier */
		if(EXIT_SUCCESS == get_cist_bridge_comp_id(result_array, MAX_NUM_OF_INTERFACES, MAX_STR_LEN, bridge_name))
		{
			strncpy(entry->ieee8021MstpCistBridgeIdentifier, result_array[0], MAX_STR_LEN);
			entry->ieee8021MstpCistBridgeIdentifier_len = strlen(entry->ieee8021MstpCistBridgeIdentifier);
		}
		else
		{
			ret = 1;/* error */
			break;
		}
		/* list ieee8021MstpCistEntry, ieee8021MstpCistTopologyChange */
		if(EXIT_SUCCESS == get_cist_bridge_topology_change(result_array, MAX_NUM_OF_INTERFACES, MAX_STR_LEN, bridge_name))
		{
			if(EXIT_FAILURE == translate_single_string_using_map(result_array[0], truth_value_map))
			{
				snmp_log(LOG_ERR, SNMP_MSG_FUN_AND_MSG, __func__, "Failed to translate topology change value!");
				ret = 1;/* error */
				break;
			}
			entry->ieee8021MstpCistTopologyChange = strtol(result_array[0], NULL, 10);
		}
		else
		{
			ret = 1;/* error */
			break;
		}
		/* list ieee8021MstpCistEntry, leaf ieee8021MstpCistBridgeIdentifier */
		if(EXIT_SUCCESS == get_cist_bridge_reg_root_identifier(result_array, MAX_NUM_OF_INTERFACES, MAX_STR_LEN, bridge_name))
		{
			strncpy(entry->ieee8021MstpCistRegionalRootIdentifier, result_array[0], MAX_STR_LEN);
			entry->ieee8021MstpCistRegionalRootIdentifier_len = strlen(entry->ieee8021MstpCistRegionalRootIdentifier);
		}
		else
		{
			ret = 1;/* error */
			break;
		}
		/* list ieee8021MstpCistEntry, leaf ieee8021MstpCistPathCost */
		if(EXIT_SUCCESS == get_cist_bridge_path_cost(result_array, MAX_NUM_OF_INTERFACES, MAX_STR_LEN, bridge_name))
		{
			entry->ieee8021MstpCistPathCost = strtoul(result_array[0], NULL, 10);
		}
		else
		{
			ret = 1;/* error */
			break;
		}
		/* list ieee8021MstpCistEntry, leaf ieee8021MstpCistMaxHops */
		if(EXIT_SUCCESS == get_cist_bridge_max_hops(result_array, MAX_NUM_OF_INTERFACES, MAX_STR_LEN, bridge_name))
		{
			entry->ieee8021MstpCistMaxHops = strtol(result_array[0], NULL, 10);
		}
		else
		{
			ret = 1;/* error */
			break;
		}
    }while(0);

    return ret;
}

/* remove a row from the table */
void
ieee8021MstpCistTable_removeEntry(netsnmp_tdata     *table_data, 
                 netsnmp_tdata_row *row) {
    struct ieee8021MstpCistTable_entry *entry;

    if (!row)
        return;    /* Nothing to remove */

    snmp_log(LOG_INFO, "ieee8021MstpCistPortTable_removeEntry entry.\n");

    entry = (struct ieee8021MstpCistTable_entry *)row->data;
    SNMP_FREE( entry );   /* XXX - release any other internal resources */

    if (table_data)
        netsnmp_tdata_remove_and_delete_row( table_data, row );
    else
        netsnmp_tdata_delete_row( row );    
}

/* cache handler */
int ieee8021MstpCistTable_load( netsnmp_cache *cache, void *vmagic ) {
    /* will be used to iterate trough ieee8021MstpCistTable_head */
    netsnmp_tdata_row *agent_row = NULL;
    /* helper to keep next agent row */
    netsnmp_tdata_row *next_agent_row = NULL;
    /* will be used to check existence of the bridge */
    netsnmp_tdata *table = (netsnmp_tdata *)vmagic;
    ieee8021MstpCistTable_entry_t *entry;
    char bridges_name[MAX_NUM_OF_INTERFACES][MAX_STR_LEN];
    int bridge_found = 0;
    
    //snmp_log(LOG_DEBUG, "%s(): is called.\n", __func__);
    
	/* gather system data */
	if(EXIT_FAILURE == get_mstp_bridge_names(bridges_name, MAX_NUM_OF_INTERFACES, MAX_STR_LEN))
	{
		snmp_log(LOG_ERR, "ERROR: %s(): Internal error. Bridges' names are unreachable.\n", __func__);
		return 1;
	}
    /* returns the first row in the table */
    agent_row = netsnmp_tdata_row_first (table);
    
    while(NULL != agent_row)
    {
        entry = (ieee8021MstpCistTable_entry_t *)agent_row->data;

        if(NULL != entry)
        {
            /* there is no more agent_row, erase it from agent */
            if(!entry->ieee8021MstpCistComponentId)
            {
                //snmp_log(LOG_DEBUG, "%s(): there is no more agent_row, erase it from agent.\n", __func__);
                /* returns next row */
                next_agent_row = netsnmp_tdata_row_next (table, agent_row);
                ieee8021MstpCistTable_removeEntry(table, agent_row);
                agent_row = next_agent_row;
                next_agent_row = NULL;
            }
            /* agent_row exists on system, skip it (leave it on agent) */
            else
            {
                //snmp_log(LOG_DEBUG, "%s(): agent_row exist on system, skip it.\n", __func__);
                /* refresh data in this existing row on agent */
                ieee8021MstpCistTable_fillEntry(bridges_name[0],
                        (ieee8021MstpCistTable_entry_t *)agent_row->data);//only one bridge is supported
                /* take next */
                agent_row = netsnmp_tdata_row_next (table, agent_row);
            }
        }
        else
        {
            snmp_log(LOG_ERR, "%s(): agent_row->data is NULL\n", __func__);
        }
    }
    /* entry (row) exists on system, but not in cache*/
    if(0 != strncmp(bridges_name[0], "", MAX_STR_LEN))
    {
        //snmp_log(LOG_DEBUG, "load: looking for bridge: %s\n", bridges_name[0]);
        /* returns the first row in the table */
        agent_row = netsnmp_tdata_row_first (table);

        while((NULL != agent_row) && (bridge_found == 0))
        {
            entry = (ieee8021MstpCistTable_entry_t *)agent_row->data;

            if(component_id == entry->ieee8021MstpCistComponentId)
            {
            	bridge_found = 1;
            }
            agent_row = netsnmp_tdata_row_next (table, agent_row);
        }
        if(bridge_found == 0)//bridge entry exists on system, but it is not in cache - add it now
        {
			snmp_log(LOG_DEBUG, "%s(): Adding new bridge: %s\n", bridges_name[0], __func__);
			agent_row = ieee8021MstpCistTable_createEntry(table, component_id);
			ieee8021MstpCistTable_fillEntry(bridges_name[0], agent_row->data);
        }
    }
        
    return 0; /* OK */
}

void ieee8021MstpCistTable_free( netsnmp_cache *cache, void *vmagic )
{
    netsnmp_tdata     *table = (netsnmp_tdata *)vmagic;
    netsnmp_tdata_row *this;

    while ((this = netsnmp_tdata_row_first(table))) {
        netsnmp_tdata_remove_and_delete_row(table, this);
    }
}

/** handles requests for the ieee8021MstpCistTable table */
int
ieee8021MstpCistTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    netsnmp_tdata              *table_data;
    netsnmp_tdata_row          *table_row;
    struct ieee8021MstpCistTable_entry          *table_entry;
    int                         ret;
    char tmp_ieee8021MstpCistMaxHops[MAX_STR_LEN] = {0};

    DEBUGMSGTL(("ieee8021MstpCistTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            if (request->processed)
                continue;

            table_entry = (struct ieee8021MstpCistTable_entry *)
                              netsnmp_tdata_extract_entry(request);
            table_info  =     netsnmp_extract_table_info( request);
    
            switch (table_info->colnum) {
            case COLUMN_IEEE8021MSTPCISTBRIDGEIDENTIFIER:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->ieee8021MstpCistBridgeIdentifier,
                                          table_entry->ieee8021MstpCistBridgeIdentifier_len);
                break;
            case COLUMN_IEEE8021MSTPCISTTOPOLOGYCHANGE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ieee8021MstpCistTopologyChange);
                break;
            case COLUMN_IEEE8021MSTPCISTREGIONALROOTIDENTIFIER:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->ieee8021MstpCistRegionalRootIdentifier,
                                          table_entry->ieee8021MstpCistRegionalRootIdentifier_len);
                break;
            case COLUMN_IEEE8021MSTPCISTPATHCOST:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->ieee8021MstpCistPathCost);
                break;
            case COLUMN_IEEE8021MSTPCISTMAXHOPS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ieee8021MstpCistMaxHops);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            if (request->processed)
                continue;
#if 0
            table_entry = (struct ieee8021MstpCistTable_entry *)
                              netsnmp_tdata_extract_entry(request);
#endif
            table_info  =     netsnmp_extract_table_info( request);
    
            switch (table_info->colnum) {
            case COLUMN_IEEE8021MSTPCISTMAXHOPS:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            if (request->processed)
                continue;

            table_entry = (struct ieee8021MstpCistTable_entry *)
                              netsnmp_tdata_extract_entry(request);
            table_info  =     netsnmp_extract_table_info( request);
    
            switch (table_info->colnum) {
            case COLUMN_IEEE8021MSTPCISTMAXHOPS:
                table_entry->old_ieee8021MstpCistMaxHops = table_entry->ieee8021MstpCistMaxHops;
                table_entry->ieee8021MstpCistMaxHops     = *request->requestvb->val.integer;
                /* because there is only on bridge on system we will use "1" */
                snprintf(tmp_ieee8021MstpCistMaxHops, MAX_STR_LEN, "%ld",
                		table_entry->ieee8021MstpCistMaxHops);
                if(EXIT_FAILURE == set_mstp_cist_max_hops("1", tmp_ieee8021MstpCistMaxHops))
				{
					netsnmp_set_request_error(reqinfo, request, SNMP_ERR_WRONGVALUE);
	                snmp_log(LOG_DEBUG, "%s(): MODE_SET_ACTION failed.\n", __func__);
					return SNMP_ERR_NOERROR;
				}
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            if (request->processed)
                continue;

            table_entry = (struct ieee8021MstpCistTable_entry *)
                              netsnmp_tdata_extract_entry(request);
#if 0
            table_row   =     netsnmp_tdata_extract_row(  request);
            table_data  =     netsnmp_tdata_extract_table(request);
#endif
            table_info  =     netsnmp_extract_table_info( request);
    
            switch (table_info->colnum) {
            case COLUMN_IEEE8021MSTPCISTMAXHOPS:
                table_entry->ieee8021MstpCistMaxHops     = table_entry->old_ieee8021MstpCistMaxHops;
                table_entry->old_ieee8021MstpCistMaxHops = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
