/*
 * TTTech ieee8021BridgeMib-mib-module
 * Copyright(c) 2019 TTTech Industrial Automation AG.
 *
 * ALL RIGHTS RESERVED.
 * Usage of this software, including source code, netlists, documentation,
 * is subject to restrictions and conditions of the applicable license
 * agreement with TTTech Industrial Automation AG or its affiliates.
 *
 * All trademarks used are the property of their respective owners.
 *
 * TTTech Industrial Automation AG and its affiliates do not assume any liability
 * arising out of the application or use of any product described or shown
 * herein. TTTech Industrial Automation AG and its affiliates reserve the right to
 * make changes, at any time, in order to improve reliability, function or
 * design.
 *
 * Contact Information:
 * support@tttech-industrial.com
 * TTTech Industrial Automation AG, Schoenbrunnerstrasse 7, 1040 Vienna, Austria
 */
/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
/* module specific */
#include "ieee8021BridgePhyPortTable.h"
#include "../ieee8021BridgeMib_helpers/ieee8021BridgeMib_helpers.h"
/* libbase includes */
#include "base_prints.h"
#include "base_linux_tool_helpers.h"
#include "base_q_bridge_linux_tools.h"
#include "base_private_translators.h"
/* libtsn includes */
#include "tsn.h"
#include "tsn_bridge.h"

/** Initializes the ieee8021BridgePhyPortTable module */
void
init_ieee8021BridgePhyPortTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_ieee8021BridgePhyPortTable();
}


/** Initialize the ieee8021BridgePhyPortTable table by defining its contents and how it's structured */
void
initialize_table_ieee8021BridgePhyPortTable(void)
{
    const oid ieee8021BridgePhyPortTable_oid[] = {1,3,111,2,802,1,1,2,1,1,6};
    const size_t ieee8021BridgePhyPortTable_oid_len   = OID_LENGTH(ieee8021BridgePhyPortTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_tdata                   *table_data;
    netsnmp_table_registration_info *table_info;
    netsnmp_cache                   *cache;

//    DEBUGMSGTL(("ieee8021BridgePhyPortTable:init", "initializing table ieee8021BridgePhyPortTable\n"));

    reg = netsnmp_create_handler_registration(
              "ieee8021BridgePhyPortTable",     ieee8021BridgePhyPortTable_handler,
              ieee8021BridgePhyPortTable_oid, ieee8021BridgePhyPortTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_data = netsnmp_tdata_create_table( "ieee8021BridgePhyPortTable", 0 );
    if (NULL == table_data) {
        snmp_log(LOG_ERR,"error creating tdata table for ieee8021BridgePhyPortTable\n");
        return;
    }
    cache = netsnmp_cache_create(IEEE8021BRIDGEPHYPORTTABLE_TIMEOUT,
                                  ieee8021BridgePhyPortTable_load, ieee8021BridgePhyPortTable_free,
                                  ieee8021BridgePhyPortTable_oid, ieee8021BridgePhyPortTable_oid_len);
    if (NULL == cache) {
        snmp_log(LOG_ERR,"error creating cache for ieee8021BridgePhyPortTable\n");
    }
    else
    {
        cache->magic = (void *)table_data;
        cache->flags =  NETSNMP_CACHE_DONT_FREE_EXPIRED     | \
                        NETSNMP_CACHE_DONT_AUTO_RELEASE     | \
                        NETSNMP_CACHE_AUTO_RELOAD           | \
                        NETSNMP_CACHE_DONT_FREE_BEFORE_LOAD | \
                        NETSNMP_CACHE_DONT_INVALIDATE_ON_SET ;
    }

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    if (NULL == table_info) {
        snmp_log(LOG_ERR,"error creating table info for ieee8021BridgePhyPortTable\n");
        return;
    }
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_UNSIGNED,  /* index: ieee8021BridgePhyPort */
                           0);

    table_info->min_column = COLUMN_IEEE8021BRIDGEPHYPORTIFINDEX;
    table_info->max_column = COLUMN_IEEE8021BRIDGEPHYPORTTOINTERNALPORT;
    
    netsnmp_tdata_register( reg, table_data, table_info );

    /* Initialise the contents of the table here */
    if(0 != init_ieee8021BridgePhyPortTable_with_sys_data(table_data))
    {
        snmp_log(LOG_ERR,"ERROR: ieee8021BridgePhyPortTable initialization was unsuccessful.\n");
        free(table_info);
        return;
    }
    else
    {
        snmp_log(LOG_INFO,"INFO: ieee8021BridgePhyPortTable initialization was successful.\n");
        netsnmp_cache_timer_start(cache);
    }
}

/* init table */
int init_ieee8021BridgePhyPortTable_with_sys_data(netsnmp_tdata *table_data)
{
    netsnmp_tdata_row *row = NULL;
    char ports_name[MAX_NUM_OF_INTERFACES][MAX_STR_LEN];
    int i = 0;
	struct port_hdl *port = NULL;
	uint32_t port_id = 0u;

    snmp_log(LOG_INFO,"called: init_ieee8021BridgePhyPortTable_with_sys_data.\n");

    /* gather system data */
    if(EXIT_FAILURE == get_bridge_port_names(ports_name, MAX_NUM_OF_INTERFACES, MAX_STR_LEN))
    {
    	snmp_log(LOG_ERR, "ERROR: get_bridge_port_names failed.\n");
        return 1;
    }

    while((i < MAX_NUM_OF_INTERFACES) && (0 != strncmp(ports_name[i], "", MAX_STR_LEN)))
    {
    	port = tsn_port_open_by_name(ports_name[i]);
    	if(NULL != port)
    	{
    	    if(0 == tsn_bridge_port_id(port, &port_id))
    	    {
    	    	row = ieee8021BridgePhyPortTable_createEntry(table_data, port_id + 1);
    			if(NULL != row)
    			{
    				ieee8021BridgePhyPortTable_fillEntry(ports_name[i], (ieee8021BridgePhyPortTable_entry_t*)row->data);
    			}
    			else
    			{
    				snmp_log(LOG_ERR, "ERROR: New row is not created.\n");
    				tsn_port_close(port);
    				/* error */
    				break;
    			}
    	    }
    	    else
    	    {
				snmp_log(LOG_ERR, "ERROR: Failed to get port id: '%s'.\n", ports_name[i]);
				tsn_port_close(port);
				break;
    	    }
    	}
    	else
    	{
            snmp_log(LOG_ERR, "port could not open: (%s)\n", ports_name[i]);
            break;
    	}
    	if(NULL != port)
    	{
    		tsn_port_close(port);
    	}
    	row = NULL;
    	i++;
    }
    /* success */
    return 0;
}

/* create a new row in the table */
netsnmp_tdata_row *
ieee8021BridgePhyPortTable_createEntry(netsnmp_tdata *table_data
                 , u_long  ieee8021BridgePhyPort
                ) {
    struct ieee8021BridgePhyPortTable_entry *entry;
    netsnmp_tdata_row *row;

    entry = SNMP_MALLOC_TYPEDEF(struct ieee8021BridgePhyPortTable_entry);
    if (!entry)
        return NULL;

    row = netsnmp_tdata_create_row();
    if (!row) {
        SNMP_FREE(entry);
        return NULL;
    }
    row->data = entry;

//    DEBUGMSGT(("ieee8021BridgePhyPortTable:entry:create", "row 0x%x\n", (uintptr_t)row));
    snmp_log(LOG_INFO,"ieee8021BridgePhyPortTable_createEntry - (%ld)\n", ieee8021BridgePhyPort);
    entry->ieee8021BridgePhyPort = ieee8021BridgePhyPort;
    netsnmp_tdata_row_add_index( row, ASN_UNSIGNED,
                                 &(entry->ieee8021BridgePhyPort),
                                 sizeof(entry->ieee8021BridgePhyPort));
    if (table_data)
        netsnmp_tdata_add_row( table_data, row );
    return row;
}

/* fill a new row data in the table */
int ieee8021BridgePhyPortTable_fillEntry(char port_name[MAX_STR_LEN],
		ieee8021BridgePhyPortTable_entry_t *entry)
{
    char result_array[MAX_NUM_OF_INTERFACES][MAX_STR_LEN];
    char tmp_result_array[MAX_NUM_OF_INTERFACES][MAX_STR_LEN];
    long int pos = 0;
    int i = 0;

    snmp_log(LOG_DEBUG, "called: ieee8021BridgePhyPortTable_fillEntry for port: '%s'\n", port_name);

    if (!entry)
    {
        snmp_log(LOG_ERR, "ieee8021BridgePhyPortTable_fillEntry:entry == NULL\n");
        /* error */
        return 1;
    }

    /* ieee8021BridgePhyPortIfIndex */
    if(EXIT_SUCCESS == get_interface_if_index(result_array, MAX_NUM_OF_INTERFACES, MAX_STR_LEN, port_name))
    {
    	entry->ieee8021BridgePhyPortIfIndex = strtol(result_array[0], NULL, 10);
    }

    /* ieee8021BridgePhyMacAddress */
    if(EXIT_SUCCESS == get_interface_address(result_array, MAX_NUM_OF_INTERFACES, MAX_STR_LEN, port_name))
    {
		memcpy(tmp_result_array[0], result_array[0], MAX_STR_LEN);
		while((i < 6) && (0 != strncmp(tmp_result_array[0], "", MAX_STR_LEN)))
		{
			pos = strcspn(tmp_result_array[0], ":");
			*(tmp_result_array[0] + pos) = '\0';
			entry->ieee8021BridgePhyMacAddress[i] = strtol(tmp_result_array[0], NULL, 16);
			i++;
			memcpy(tmp_result_array[0], (result_array[0] + pos + 1), MAX_STR_LEN);
		}
    	entry->ieee8021BridgePhyMacAddress_len = sizeof(entry->ieee8021BridgePhyMacAddress);
    }

    /* ieee8021BridgePhyPortToComponentId, there is only one bridge/component, hardcoded to "1" */
    entry->ieee8021BridgePhyPortToComponentId = 1;

    return 0;
}

/* remove a row from the table */
void
ieee8021BridgePhyPortTable_removeEntry(netsnmp_tdata     *table_data, 
                 netsnmp_tdata_row *row) {
    struct ieee8021BridgePhyPortTable_entry *entry;

    if (!row)
        return;    /* Nothing to remove */

    //DEBUGMSGT(("ieee8021BridgePhyPortTable:entry:remove", "row 0x%x\n", (uintptr_t)row));

    entry = (struct ieee8021BridgePhyPortTable_entry *)row->data;
    SNMP_FREE( entry );   /* XXX - release any other internal resources */

    if (table_data)
        netsnmp_tdata_remove_and_delete_row( table_data, row );
    else
        netsnmp_tdata_delete_row( row );    
}

/* Example cache handling - set up table_data list from a suitable file */
int
ieee8021BridgePhyPortTable_load( netsnmp_cache *cache, void *vmagic ) {
	/* will be used to iterate trough ieee8021BridgeBaseTable_head */
	netsnmp_tdata_row *agent_row = NULL;
	/* helper to keep next agent row */
	netsnmp_tdata_row *next_agent_row = NULL;
	/* will be used to check existence of the bridge */
	netsnmp_tdata *table = (netsnmp_tdata *)vmagic;
    ieee8021BridgePhyPortTable_entry_t *entry = NULL;
    int port_found = 0;
    char ports_name[MAX_NUM_OF_INTERFACES][MAX_STR_LEN];
	struct port_hdl *port = NULL;
	uint32_t port_id = 0u;
    int i = 0;
    char port_name[MAX_STR_LEN];

    snmp_log(LOG_DEBUG, "called: ieee8021BridgePhyPortTable_load\n");

    /* gather fresh system data */
    if(EXIT_FAILURE == get_bridge_port_names(ports_name, MAX_NUM_OF_INTERFACES, MAX_STR_LEN))
    {
    	snmp_log(LOG_ERR, "ERROR: get_bridge_port_names failed.\n");
        return 1;
    }

    /* returns the first row in the table */
    agent_row = netsnmp_tdata_row_first (table);

    while(NULL != agent_row)
    {
        snmp_log(LOG_ERR, "Agent row exists.\n");
        entry = (ieee8021BridgePhyPortTable_entry_t *)agent_row->data;

        if(NULL != entry)
        {
            /* check if this entry (bridge) exist on system*/
            /* there is no more agent_row, erase it from agent */
            if(!entry->ieee8021BridgePhyPort)
            {
                snmp_log(LOG_DEBUG, "there is no more agent_row, erase it from agent\n");
                /* returns next row */
                next_agent_row = netsnmp_tdata_row_next (table, agent_row);
                ieee8021BridgePhyPortTable_removeEntry(table, agent_row);
                agent_row = next_agent_row;
                next_agent_row = NULL;
            }
            /* agent_row exist on system, skip it (leave it on agent) */
            else
            {
                snmp_log(LOG_DEBUG, "agent_row exist on system, skip it\n");
				if(EXIT_FAILURE == get_port_name_by_tsn_port_id(entry->ieee8021BridgePhyPort, port_name))
				{
					snmp_log(LOG_ERR, "error: get_port_name_by_tsn_port_id returns EXIT_FAILURE\n");
					return 1;
				}
				if(NULL != port_name)
				{
					ieee8021BridgePhyPortTable_fillEntry(port_name,
							(ieee8021BridgePhyPortTable_entry_t *)agent_row->data);
				}
                /* take next */
                agent_row = netsnmp_tdata_row_next (table, agent_row);
            }
        }
        else
        {
            snmp_log(LOG_ERR, "error: agent_row->data is NULL\n");
        }
    }

    i = 0;
    while((i < MAX_NUM_OF_INTERFACES) && (0 != strncmp(ports_name[i], "", MAX_STR_LEN)))
    {
        snmp_log(LOG_DEBUG, "load: looking for port: %s\n", ports_name[i]);
		port = tsn_port_open_by_name(ports_name[i]);
		if(NULL == port)
		{
			snmp_log(LOG_ERR, "port could not open: '%s'\n", ports_name[i]);
			/* error */
			break;
		}
		if(0 != tsn_bridge_port_id(port, &port_id))
		{
			snmp_log(LOG_ERR, "could not get port id: '%s'\n", ports_name[i]);
			tsn_port_close(port);
			/* error */
			break;
		}
		tsn_port_close(port);
        /* returns the first row in the table */
        agent_row = netsnmp_tdata_row_first (table);

        while((NULL != agent_row) && (port_found == 0))
        {
            entry = (ieee8021BridgePhyPortTable_entry_t *)agent_row->data;

            if((entry->ieee8021BridgePhyPort == (port_id + 1)))
            {
                port_found = 1;
            }

            agent_row = netsnmp_tdata_row_next (table, agent_row);
        }

        if(port_found == 0)
        {
            snmp_log(LOG_DEBUG, "load: Adding new bridge: %s\n", ports_name[i]);
            agent_row = ieee8021BridgePhyPortTable_createEntry(table, port_id + 1);
            ieee8021BridgePhyPortTable_fillEntry(ports_name[i], agent_row->data);
        }
        i++;
        port_found = 0;
    }

    return 0;  /* OK */
}

void
ieee8021BridgePhyPortTable_free( netsnmp_cache *cache, void *vmagic ) {
    netsnmp_tdata     *table = (netsnmp_tdata *)vmagic;
    netsnmp_tdata_row *this;

    while ((this = netsnmp_tdata_row_first(table))) {
        netsnmp_tdata_remove_and_delete_row(table, this);
    }
}

/** handles requests for the ieee8021BridgePhyPortTable table */
int
ieee8021BridgePhyPortTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    netsnmp_tdata              *table_data;
    netsnmp_tdata_row          *table_row;
    struct ieee8021BridgePhyPortTable_entry          *table_entry;
    int                         ret;

//    DEBUGMSGTL(("ieee8021BridgePhyPortTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            if (request->processed)
                continue;

            table_entry = (struct ieee8021BridgePhyPortTable_entry *)
                              netsnmp_tdata_extract_entry(request);
            table_info  =     netsnmp_extract_table_info( request);
    
            switch (table_info->colnum) {
            case COLUMN_IEEE8021BRIDGEPHYPORTIFINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ieee8021BridgePhyPortIfIndex);
                break;
            case COLUMN_IEEE8021BRIDGEPHYMACADDRESS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->ieee8021BridgePhyMacAddress,
                                          table_entry->ieee8021BridgePhyMacAddress_len);
                break;
            case COLUMN_IEEE8021BRIDGEPHYPORTTOCOMPONENTID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->ieee8021BridgePhyPortToComponentId);
                break;
#if 0
            case COLUMN_IEEE8021BRIDGEPHYPORTTOINTERNALPORT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->ieee8021BridgePhyPortToInternalPort);
                break;
#endif
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;
    }
    return SNMP_ERR_NOERROR;
}
