/*
 * TTTech ieee8021BridgeMib-mib-module
 * Copyright(c) 2019 TTTech Industrial Automation AG.
 *
 * ALL RIGHTS RESERVED.
 * Usage of this software, including source code, netlists, documentation,
 * is subject to restrictions and conditions of the applicable license
 * agreement with TTTech Industrial Automation AG or its affiliates.
 *
 * All trademarks used are the property of their respective owners.
 *
 * TTTech Industrial Automation AG and its affiliates do not assume any liability
 * arising out of the application or use of any product described or shown
 * herein. TTTech Industrial Automation AG and its affiliates reserve the right to
 * make changes, at any time, in order to improve reliability, function or
 * design.
 *
 * Contact Information:
 * support@tttech-industrial.com
 * TTTech Industrial Automation AG, Schoenbrunnerstrasse 7, 1040 Vienna, Austria
 */
/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef IEEE8021BRIDGEPHYPORTTABLE_H
#define IEEE8021BRIDGEPHYPORTTABLE_H

#include "base_prints.h"

typedef struct ieee8021BridgePhyPortTable_entry ieee8021BridgePhyPortTable_entry_t;

/* function declarations */
void init_ieee8021BridgePhyPortTable(void);
void initialize_table_ieee8021BridgePhyPortTable(void);
int init_ieee8021BridgePhyPortTable_with_sys_data(netsnmp_tdata *table_data);
netsnmp_tdata_row* ieee8021BridgePhyPortTable_createEntry(netsnmp_tdata *table_data, u_long ieee8021BridgePhyPort);
int ieee8021BridgePhyPortTable_fillEntry(char port_name[MAX_STR_LEN],
		ieee8021BridgePhyPortTable_entry_t *entry);
Netsnmp_Node_Handler ieee8021BridgePhyPortTable_handler;
NetsnmpCacheLoad ieee8021BridgePhyPortTable_load;
NetsnmpCacheFree ieee8021BridgePhyPortTable_free;
#define IEEE8021BRIDGEPHYPORTTABLE_TIMEOUT  60

/* column number definitions for table ieee8021BridgePhyPortTable */
#define COLUMN_IEEE8021BRIDGEPHYPORT					1
#define COLUMN_IEEE8021BRIDGEPHYPORTIFINDEX				2
#define COLUMN_IEEE8021BRIDGEPHYMACADDRESS				3
#define COLUMN_IEEE8021BRIDGEPHYPORTTOCOMPONENTID		4
#define COLUMN_IEEE8021BRIDGEPHYPORTTOINTERNALPORT		5

/* Typical data structure for a row entry */
struct ieee8021BridgePhyPortTable_entry {
    /* Index values */
    u_long ieee8021BridgePhyPort;

    /* Column values */
    long ieee8021BridgePhyPortIfIndex;
    char ieee8021BridgePhyMacAddress[6];
    size_t ieee8021BridgePhyMacAddress_len;
    u_long ieee8021BridgePhyPortToComponentId;
    u_long ieee8021BridgePhyPortToInternalPort;

    int   valid;
};

#endif /* IEEE8021BRIDGEPHYPORTTABLE_H */
