/*
 * TTTech libbase
 * Copyright(c) 2019 TTTech Computertechnik AG.
 *
 * ALL RIGHTS RESERVED.
 * Usage of this software, including source code, netlists, documentation,
 * is subject to restrictions and conditions of the applicable license
 * agreement with TTTech Computertechnik AG or its affiliates.
 *
 * All trademarks used are the property of their respective owners.
 *
 * TTTech Computertechnik AG and its affiliates do not assume any liability
 * arising out of the application or use of any product described or shown
 * herein. TTTech Computertechnik AG and its affiliates reserve the right to
 * make changes, at any time, in order to improve reliability, function or
 * design.
 *
 * Contact Information:
 * support@4me.tttech-dependablenetworks.com
 * TTTech Computertechnik AG, Schoenbrunnerstrasse 7, 1040 Vienna, Austria
 */

#include "base_private_defines.h"
#include "base_mstp_linux_tools.h"
#include "base_private_parsers.h"
#include "base_private_validators.h"
#include "base_private_combinators.h"

char mstp_map[MSTP_MAX_OBJ_NUMBER][MAX_STR_LEN] = {
    // map between object index and object name for mstp module
    [MSTPD]                          = MSTPD_STR,
    [MSTP_MODULE]                    = MSTP_NAME,
    [MSTP_BRIDGE_NAMES]              = MSTP_BRIDGE_NAMES_STR,
    [MSTP_PORT_NAMES]                = MSTP_PORT_NAMES_STR,
    [MSTP_PORT_NUM]                  = MSTP_PORT_NUM_STR, // for all types of port num
    [MSTP_CIST_TABLE]                = MSTP_CIST_TABLE_STR,
    [MSTP_CIST_BRIDGE_ID]            = MSTP_CIST_BRIDGE_ID_STR,
    [MSTP_CIST_TOP_CHANGE]           = MSTP_CIST_TOP_CHANGE_STR,
    [MSTP_CIST_REG_ROOT_ID]          = MSTP_CIST_REG_ROOT_ID_STR,
    [MSTP_CIST_PATH_COST]            = MSTP_CIST_PATH_COST_STR,
    [MSTP_CIST_BRIDGE_PRIO]          = MSTP_CIST_BRIDGE_PRIO_STR,
    [MSTP_ENTRY_ADD]                 = MSTP_ENTRY_ADD_STR,
    [MSTP_ENTRY_DEL]                 = MSTP_ENTRY_DEL_STR,
    [MSTP_DEL_FIDS]                  = MSTP_DEL_FIDS_STR,
    [MSTP_SET_FID_2_MSTID]           = MSTP_SET_FID_2_MSTID_STR,
    [MSTP_SET_VID_2_FID]             = MSTP_SET_VID_2_FID_STR,
    [MSTP_CIST_MAX_HOPS]             = MSTP_CIST_MAX_HOPS_STR,
    [MSTP_ID]                        = MSTP_ID_STR,
    [MSTP_BRIDGE_ID]                 = MSTP_BRIDGE_ID_STR,
    [MSTP_SINCE_TOP_CHANGE]          = MSTP_SINCE_TOP_CHANGE_STR,
    [MSTP_TOP_CHANGES]               = MSTP_TOP_CHANGES_STR,
    [MSTP_DSGN_ROOT]                 = MSTP_DSGN_ROOT_STR,
    [MSTP_ROOT_PATH_COST]            = MSTP_ROOT_PATH_COST_STR,
    [MSTP_ROOT_PORT]                 = MSTP_ROOT_PORT_STR,
    [MSTP_TABLE]                     = MSTP_TABLE_STR,
    [MSTP_BRIDGE_PRIORITY]           = MSTP_BRIDGE_PRIORITY_STR,
    [MSTP_CIST_PORT_TABLE]           = MSTP_CIST_PORT_TABLE_STR,
    [MSTP_CIST_PORT_DSGN_ROOT]       = MSTP_CIST_PORT_DSGN_ROOT_STR,
    [MSTP_CIST_PORT_TOP_CHANGE_ACK]  = MSTP_CIST_PORT_TOP_CHANGE_ACK_STR,
    [MSTP_CIST_PORT_HELLO_TIME]      = MSTP_CIST_PORT_HELLO_TIME_STR,
    [MSTP_CIST_PORT_OPER_EDGE_PORT]  = MSTP_CIST_PORT_OPER_EDGE_PORT_STR,
    [MSTP_CIST_PORT_PORT_ROLE]       = MSTP_CIST_PORT_PORT_ROLE_STR,
    [MSTP_CIST_PORT_DISPUTED]        = MSTP_CIST_PORT_DISPUTED_STR,
    [MSTP_CIST_PORT_REG_ROOT_ID]     = MSTP_CIST_PORT_REG_ROOT_ID_STR,
    [MSTP_CIST_PORT_PATH_COST]       = MSTP_CIST_PORT_PATH_COST_STR,
    [MSTP_CIST_PORT_ADMIN_PATH_COST] = MSTP_CIST_PORT_ADMIN_PATH_COST_STR,
    [MSTP_CIST_PORT_ADMIN_EDGE_PORT] = MSTP_CIST_PORT_ADMIN_EDGE_PORT_STR,
    [MSTP_CIST_PORT_MAC_ENABLED]     = MSTP_CIST_PORT_MAC_ENABLED_STR,
    [MSTP_CIST_PORT_RESTR_ROLE]      = MSTP_CIST_PORT_RESTR_ROLE_STR,
    [MSTP_CIST_PORT_RESTR_TCN]       = MSTP_CIST_PORT_RESTR_TCN_STR,
    [MSTP_PORT_TABLE]                = MSTP_PORT_TABLE_STR,
    [MSTP_PORT_STATE]                = MSTP_PORT_STATE_STR,
    [MSTP_PORT_DSGN_ROOT]            = MSTP_PORT_DSGN_ROOT_STR,
    [MSTP_PORT_DSGN_COST]            = MSTP_PORT_DSGN_COST_STR,
    [MSTP_PORT_DSGN_BRIDGE]          = MSTP_PORT_DSGN_BRIDGE_STR,
    [MSTP_PORT_DSGN_PORT]            = MSTP_PORT_DSGN_PORT_STR,
    [MSTP_PORT_ROLE]                 = MSTP_PORT_ROLE_STR,
    [MSTP_PORT_DISPUTED]             = MSTP_PORT_DISPUTED_STR,
    [MSTP_PORT_PRIORITY]             = MSTP_PORT_PRIORITY_STR,
    [MSTP_PORT_PATH_COST]            = MSTP_PORT_PATH_COST_STR,
    [MSTP_CONF_ID_TABLE]             = MSTP_CONF_ID_TABLE_STR,
    [MSTP_CONF_ID_SELECTOR]          = MSTP_CONF_ID_SELECTOR_STR,
    [MSTP_CONF_ID_CONF_NAME]         = MSTP_CONF_ID_CONF_NAME_STR,
    [MSTP_CONF_ID_REVISION]          = MSTP_CONF_ID_REVISION_STR,
    [MSTP_CONF_DIGEST]               = MSTP_CONF_DIGEST_STR,
    [MSTP_PORT_ADMIN_P2P]            = MSTP_PORT_ADMIN_P2P_STR,
};

// Commands used for get system calls
char mstp_get_sys_call_commands[MSTP_MAX_OBJ_NUMBER][MAX_STR_LEN] = {
    [MSTPD]                          = "ps aux",
    [MSTP_BRIDGE_NAMES]              = "mstpctl showbridge",
    [MSTP_PORT_NAMES]                = "mstpctl showportdetail %s",
    [MSTP_PORT_NUM]                  = "mstpctl showportdetail %s %s port-id",
    [MSTP_CIST_BRIDGE_ID]            = "mstpctl showbridge %s bridge-id",
    [MSTP_CIST_TOP_CHANGE]           = "mstpctl showbridge %s topology-change",
    [MSTP_CIST_REG_ROOT_ID]          = "mstpctl showbridge %s regional-root",
    [MSTP_CIST_PATH_COST]            = "mstpctl showbridge %s path-cost",
    [MSTP_CIST_BRIDGE_PRIO]          = "mstpctl showbridge %s bridge-id",
    [MSTP_CIST_MAX_HOPS]             = "mstpctl showbridge %s",
    [MSTP_ID]                        = "mstpctl showmstilist %s",
    [MSTP_BRIDGE_ID]                 = "mstpctl showtree %s %s",
    [MSTP_SINCE_TOP_CHANGE]          = "mstpctl showtree %s %s",
    [MSTP_TOP_CHANGES]               = "mstpctl showtree %s %s",
    [MSTP_DSGN_ROOT]                 = "mstpctl showbridge %s designated-root",
    [MSTP_ROOT_PATH_COST]            = "mstpctl showtree %s %s",
    [MSTP_ROOT_PORT]                 = "mstpctl showtree %s %s",
    [MSTP_BRIDGE_PRIORITY]           = "mstpctl showtree %s %s",
    [MSTP_CIST_PORT_DSGN_ROOT]       = "mstpctl showportdetail %s %s designated-root",
    [MSTP_CIST_PORT_TOP_CHANGE_ACK]  = "mstpctl showportdetail %s %s topology-change-ack",
    [MSTP_CIST_PORT_HELLO_TIME]      = "mstpctl showportdetail %s %s port-hello-time",
    [MSTP_CIST_PORT_OPER_EDGE_PORT]  = "mstpctl showportdetail %s %s oper-edge-port",
    [MSTP_CIST_PORT_PORT_ROLE]       = "mstpctl showportdetail %s %s role",
    [MSTP_CIST_PORT_DISPUTED]        = "mstpctl showportdetail %s %s disputed",
    [MSTP_CIST_PORT_REG_ROOT_ID]     = "mstpctl showportdetail %s %s dsgn-regional-root",
    [MSTP_CIST_PORT_PATH_COST]       = "mstpctl showportdetail %s %s dsgn-internal-cost",
    [MSTP_CIST_PORT_ADMIN_PATH_COST] = "mstpctl showportdetail %s %s admin-external-cost",
    [MSTP_CIST_PORT_ADMIN_EDGE_PORT] = "mstpctl showportdetail %s %s admin-edge-port",
    [MSTP_CIST_PORT_MAC_ENABLED]     = "mstpctl showportdetail %s %s point-to-point",
    [MSTP_CIST_PORT_RESTR_ROLE]      = "mstpctl showportdetail %s %s restricted-role",
    [MSTP_CIST_PORT_RESTR_TCN]       = "mstpctl showportdetail %s %s restricted-TCN",
    [MSTP_PORT_STATE]                = "mstpctl showtreeport %s %s %s",
    [MSTP_PORT_DSGN_ROOT]            = "mstpctl showtreeport %s %s %s",
    [MSTP_PORT_DSGN_COST]            = "mstpctl showtreeport %s %s %s",
    [MSTP_PORT_DSGN_BRIDGE]          = "mstpctl showtreeport %s %s %s",
    [MSTP_PORT_DSGN_PORT]            = "mstpctl showtreeport %s %s %s",
    [MSTP_PORT_ROLE]                 = "mstpctl showtreeport %s %s %s",
    [MSTP_PORT_DISPUTED]             = "mstpctl showtreeport %s %s %s",
    [MSTP_PORT_PRIORITY]             = "mstpctl showtreeport %s %s %s",
    [MSTP_PORT_PATH_COST]            = "mstpctl showtreeport %s %s %s",
    [MSTP_CONF_ID_SELECTOR]          = "mstpctl showmstconfid %s",
    [MSTP_CONF_ID_CONF_NAME]         = "mstpctl showmstconfid %s",
    [MSTP_CONF_ID_REVISION]          = "mstpctl showmstconfid %s",
    [MSTP_CONF_DIGEST]               = "mstpctl showmstconfid %s",
    [MSTP_PORT_ADMIN_P2P]            = "mstpctl showportdetail %s %s admin-point-to-point",
};

syscall_fn_t mstp_syscalls[MSTP_MAX_OBJ_NUMBER] = {
    [MSTPD]                          = (syscall_fn_t)&get_str_sys_call,
    [MSTP_BRIDGE_NAMES]              = (syscall_fn_t)&get_str_sys_call,
    [MSTP_PORT_NAMES]                = (syscall_fn_t)&get_str_sys_call,
    [MSTP_PORT_NUM]                  = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CIST_BRIDGE_ID]            = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CIST_TOP_CHANGE]           = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CIST_REG_ROOT_ID]          = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CIST_PATH_COST]            = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CIST_BRIDGE_PRIO]          = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CIST_MAX_HOPS]             = (syscall_fn_t)&get_str_sys_call,
    [MSTP_ID]                        = (syscall_fn_t)&get_str_sys_call,
    [MSTP_BRIDGE_ID]                 = (syscall_fn_t)&get_str_sys_call,
    [MSTP_SINCE_TOP_CHANGE]          = (syscall_fn_t)&get_str_sys_call,
    [MSTP_TOP_CHANGES]               = (syscall_fn_t)&get_str_sys_call,
    [MSTP_DSGN_ROOT]                 = (syscall_fn_t)&get_str_sys_call,
    [MSTP_ROOT_PATH_COST]            = (syscall_fn_t)&get_str_sys_call,
    [MSTP_ROOT_PORT]                 = (syscall_fn_t)&get_str_sys_call,
    [MSTP_BRIDGE_PRIORITY]           = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CIST_PORT_DSGN_ROOT]       = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CIST_PORT_TOP_CHANGE_ACK]  = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CIST_PORT_HELLO_TIME]      = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CIST_PORT_OPER_EDGE_PORT]  = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CIST_PORT_PORT_ROLE]       = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CIST_PORT_DISPUTED]        = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CIST_PORT_REG_ROOT_ID]     = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CIST_PORT_PATH_COST]       = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CIST_PORT_ADMIN_PATH_COST] = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CIST_PORT_ADMIN_EDGE_PORT] = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CIST_PORT_MAC_ENABLED]     = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CIST_PORT_RESTR_ROLE]      = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CIST_PORT_RESTR_TCN]       = (syscall_fn_t)&get_str_sys_call,
    [MSTP_PORT_STATE]                = (syscall_fn_t)&get_str_sys_call,
    [MSTP_PORT_DSGN_ROOT]            = (syscall_fn_t)&get_str_sys_call,
    [MSTP_PORT_DSGN_COST]            = (syscall_fn_t)&get_str_sys_call,
    [MSTP_PORT_DSGN_BRIDGE]          = (syscall_fn_t)&get_str_sys_call,
    [MSTP_PORT_DSGN_PORT]            = (syscall_fn_t)&get_str_sys_call,
    [MSTP_PORT_ROLE]                 = (syscall_fn_t)&get_str_sys_call,
    [MSTP_PORT_DISPUTED]             = (syscall_fn_t)&get_str_sys_call,
    [MSTP_PORT_PRIORITY]             = (syscall_fn_t)&get_str_sys_call,
    [MSTP_PORT_PATH_COST]            = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CONF_ID_SELECTOR]          = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CONF_ID_CONF_NAME]         = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CONF_ID_REVISION]          = (syscall_fn_t)&get_str_sys_call,
    [MSTP_CONF_DIGEST]               = (syscall_fn_t)&get_str_sys_call,
    [MSTP_PORT_ADMIN_P2P]            = (syscall_fn_t)&get_str_sys_call,
};

// Number of combinators per system call (object index)
int mstp_num_of_combinators[MSTP_MAX_OBJ_NUMBER] = {
    [MSTPD]                          = 2,
    [MSTP_BRIDGE_NAMES]              = 2,
    [MSTP_PORT_NAMES]                = 2,
    [MSTP_PORT_NUM]                  = 4,
    [MSTP_CIST_BRIDGE_ID]            = 2,
    [MSTP_CIST_TOP_CHANGE]           = 4,
    [MSTP_CIST_REG_ROOT_ID]          = 2,
    [MSTP_CIST_PATH_COST]            = 2,
    [MSTP_CIST_BRIDGE_PRIO]          = 5,
    [MSTP_CIST_MAX_HOPS]             = 4,
    [MSTP_ID]                        = 3,
    [MSTP_BRIDGE_ID]                 = 2,
    [MSTP_SINCE_TOP_CHANGE]          = 2,
    [MSTP_TOP_CHANGES]               = 2,
    [MSTP_DSGN_ROOT]                 = 2,
    [MSTP_ROOT_PATH_COST]            = 2,
    [MSTP_ROOT_PORT]                 = 2,
    [MSTP_BRIDGE_PRIORITY]           = 5,
    [MSTP_CIST_PORT_DSGN_ROOT]       = 2,
    [MSTP_CIST_PORT_TOP_CHANGE_ACK]  = 4,
    [MSTP_CIST_PORT_HELLO_TIME]      = 3,
    [MSTP_CIST_PORT_OPER_EDGE_PORT]  = 4,
    [MSTP_CIST_PORT_PORT_ROLE]       = 2,
    [MSTP_CIST_PORT_DISPUTED]        = 4,
    [MSTP_CIST_PORT_REG_ROOT_ID]     = 2,
    [MSTP_CIST_PORT_PATH_COST]       = 2,
    [MSTP_CIST_PORT_ADMIN_PATH_COST] = 2,
    [MSTP_CIST_PORT_ADMIN_EDGE_PORT] = 4,
    [MSTP_CIST_PORT_MAC_ENABLED]     = 4,
    [MSTP_CIST_PORT_RESTR_ROLE]      = 4,
    [MSTP_CIST_PORT_RESTR_TCN]       = 4,
    [MSTP_PORT_STATE]                = 2,
    [MSTP_PORT_DSGN_ROOT]            = 2,
    [MSTP_PORT_DSGN_COST]            = 2,
    [MSTP_PORT_DSGN_BRIDGE]          = 2,
    [MSTP_PORT_DSGN_PORT]            = 4,
    [MSTP_PORT_ROLE]                 = 7,
    [MSTP_PORT_DISPUTED]             = 4,
    [MSTP_PORT_PRIORITY]             = 5,
    [MSTP_PORT_PATH_COST]            = 2,
    [MSTP_CONF_ID_SELECTOR]          = 2,
    [MSTP_CONF_ID_CONF_NAME]         = 2,
    [MSTP_CONF_ID_REVISION]          = 2,
    [MSTP_CONF_DIGEST]               = 2,
    [MSTP_PORT_ADMIN_P2P]            = 5,
};

combinator_fn_t mstp_combinators[MSTP_MAX_OBJ_NUMBER][MAX_COMBINATORS_NUM] = {
    [MSTPD]                          = {&combinator_comb, &AND_combinator},
    [MSTP_BRIDGE_NAMES]              = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_PORT_NAMES]                = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_PORT_NUM]                  = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator},
    [MSTP_CIST_BRIDGE_ID]            = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_CIST_TOP_CHANGE]           = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator},
    [MSTP_CIST_REG_ROOT_ID]          = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_CIST_PATH_COST]            = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_CIST_BRIDGE_PRIO]          = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator, &no_combinator},
    [MSTP_CIST_MAX_HOPS]             = {&combinator_comb, &repeat_until_null_with_check, &no_combinator , &no_combinator},
    [MSTP_ID]                        = {&combinator_comb, &repeat_until_null_with_check, &no_combinator},
    [MSTP_BRIDGE_ID]                 = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_SINCE_TOP_CHANGE]          = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_TOP_CHANGES]               = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_DSGN_ROOT]                 = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_ROOT_PATH_COST]            = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_ROOT_PORT]                 = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_BRIDGE_PRIORITY]           = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator, &no_combinator},
    [MSTP_CIST_PORT_DSGN_ROOT]       = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_CIST_PORT_TOP_CHANGE_ACK]  = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator},
    [MSTP_CIST_PORT_HELLO_TIME]      = {&combinator_comb, &repeat_until_null_with_check, &no_combinator},
    [MSTP_CIST_PORT_OPER_EDGE_PORT]  = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator},
    [MSTP_CIST_PORT_PORT_ROLE]       = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_CIST_PORT_DISPUTED]        = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator},
    [MSTP_CIST_PORT_REG_ROOT_ID]     = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_CIST_PORT_PATH_COST]       = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_CIST_PORT_ADMIN_PATH_COST] = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_CIST_PORT_ADMIN_EDGE_PORT] = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator},
    [MSTP_CIST_PORT_MAC_ENABLED]     = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator},
    [MSTP_CIST_PORT_RESTR_ROLE]      = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator},
    [MSTP_CIST_PORT_RESTR_TCN]       = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator},
    [MSTP_PORT_STATE]                = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_PORT_DSGN_ROOT]            = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_PORT_DSGN_COST]            = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_PORT_DSGN_BRIDGE]          = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_PORT_DSGN_PORT]            = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator},
    [MSTP_PORT_ROLE]                 = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator, &no_combinator, &no_combinator, &no_combinator},
    [MSTP_PORT_DISPUTED]             = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator},
    [MSTP_PORT_PRIORITY]             = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator, &no_combinator},
    [MSTP_PORT_PATH_COST]            = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_CONF_ID_SELECTOR]          = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_CONF_ID_CONF_NAME]         = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_CONF_ID_REVISION]          = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_CONF_DIGEST]               = {&combinator_comb, &repeat_until_null_with_check},
    [MSTP_PORT_ADMIN_P2P]            = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator, &no_combinator},
};

// We need a number of callbacks per combinator if we are using more than one
int mstp_num_of_cb[MSTP_MAX_OBJ_NUMBER][MAX_COMBINATORS_NUM] = {
    // A combinator uses a predefined amount of callbacks, actually set here
    [MSTPD]                          = {0, 2},
    [MSTP_BRIDGE_NAMES]              = {0, 2},
    [MSTP_PORT_NAMES]                = {0, 2},
    [MSTP_PORT_NUM]                  = {0, 1, 1, 1},
    [MSTP_CIST_BRIDGE_ID]            = {0, 1},
    [MSTP_CIST_TOP_CHANGE]           = {0, 1, 1, 1},
    [MSTP_CIST_REG_ROOT_ID]          = {0, 1},
    [MSTP_CIST_PATH_COST]            = {0, 1},
    [MSTP_CIST_BRIDGE_PRIO]          = {0, 1, 1, 1, 1},
    [MSTP_CIST_MAX_HOPS]             = {0, 1, 1, 1},
    [MSTP_ID]                        = {0, 1, 1},
    [MSTP_BRIDGE_ID]                 = {0, 1},
    [MSTP_SINCE_TOP_CHANGE]          = {0, 1},
    [MSTP_TOP_CHANGES]               = {0, 1},
    [MSTP_DSGN_ROOT]                 = {0, 1},
    [MSTP_ROOT_PATH_COST]            = {0, 1},
    [MSTP_ROOT_PORT]                 = {0, 1},
    [MSTP_BRIDGE_PRIORITY]           = {0, 1, 1, 1, 1},
    [MSTP_CIST_PORT_DSGN_ROOT]       = {0, 1},
    [MSTP_CIST_PORT_TOP_CHANGE_ACK]  = {0, 1, 1, 1},
    [MSTP_CIST_PORT_HELLO_TIME]      = {0, 2, 1},
    [MSTP_CIST_PORT_OPER_EDGE_PORT]  = {0, 1, 1, 1},
    [MSTP_CIST_PORT_PORT_ROLE]       = {0, 1},
    [MSTP_CIST_PORT_DISPUTED]        = {0, 1, 1, 1},
    [MSTP_CIST_PORT_REG_ROOT_ID]     = {0, 1},
    [MSTP_CIST_PORT_PATH_COST]       = {0, 2},
    [MSTP_CIST_PORT_ADMIN_PATH_COST] = {0, 2},
    [MSTP_CIST_PORT_ADMIN_EDGE_PORT] = {0, 1, 1, 1},
    [MSTP_CIST_PORT_MAC_ENABLED]     = {0, 1, 1, 1},
    [MSTP_CIST_PORT_RESTR_ROLE]      = {0, 1, 1, 1},
    [MSTP_CIST_PORT_RESTR_TCN]       = {0, 1, 1, 1},
    [MSTP_PORT_STATE]                = {0, 1},
    [MSTP_PORT_DSGN_ROOT]            = {0, 1},
    [MSTP_PORT_DSGN_COST]            = {0, 1},
    [MSTP_PORT_DSGN_BRIDGE]          = {0, 1},
    [MSTP_PORT_DSGN_PORT]            = {0, 1, 1, 1},
    [MSTP_PORT_ROLE]                 = {0, 1, 1, 1, 1, 1, 1},
    [MSTP_PORT_DISPUTED]             = {0, 1, 1, 1},
    [MSTP_PORT_PRIORITY]             = {0, 1, 1, 1, 1},
    [MSTP_PORT_PATH_COST]            = {0, 1},
    [MSTP_CONF_ID_SELECTOR]          = {0, 1},
    [MSTP_CONF_ID_CONF_NAME]         = {0, 2},
    [MSTP_CONF_ID_REVISION]          = {0, 1},
    [MSTP_CONF_DIGEST]               = {0, 1},
    [MSTP_PORT_ADMIN_P2P]            = {0, 1, 1, 1, 1},
};

// read it like: callbacks at object index, at combinator index
parser_spec_t mstp_parsing_cb[MSTP_MAX_OBJ_NUMBER][MAX_COMBINATORS_NUM][MAX_CALLBACKS_NUM] = {
    [MSTPD]                         [1] = {{&find_on_line, MSTPD_STR}, {&is_not_on_line, GREP_STR}},
    [MSTP_BRIDGE_NAMES]             [1] = {{&find_on_line, CIST_INFO_STR}, {&get_first_word, ""}},
    [MSTP_PORT_NAMES]               [1] = {{&find_on_line, CIST_INFO_STR}, {&find_and_get_next_word, COLON_STR}},
    [MSTP_PORT_NUM]                 [1] = {{&get_first_word, ""}},
    [MSTP_PORT_NUM]                 [2] = {{&array_take_value_after, POINT_STR}},
    [MSTP_PORT_NUM]                 [3] = {{&array_bitwise_AND_mask, X0F_MASK_STR}},
    [MSTP_CIST_BRIDGE_ID]           [1] = {{&get_first_word, ""}},
    [MSTP_CIST_TOP_CHANGE]          [1] = {{&get_first_word, ""}},
    [MSTP_CIST_TOP_CHANGE]          [2] = {{&validate_string_content, BASE_YES}},
    [MSTP_CIST_TOP_CHANGE]          [3] = {{&validate_string_content, BASE_NO}},
    [MSTP_CIST_REG_ROOT_ID]         [1] = {{&get_first_word, ""}},
    [MSTP_CIST_PATH_COST]           [1] = {{&get_first_word, ""}},
    [MSTP_CIST_BRIDGE_PRIO]         [1] = {{&get_first_word, ""}},
    [MSTP_CIST_BRIDGE_PRIO]         [2] = {{&array_drop_punctuation, ""}},
    [MSTP_CIST_BRIDGE_PRIO]         [3] = {{&array_shrink_string, BASE_ONE_STR}},
    [MSTP_CIST_BRIDGE_PRIO]         [4] = {{&array_convert_hex_string_to_long_int, ""}},
    [MSTP_CIST_MAX_HOPS]            [1] = {{&find_and_get_next_word, MAX_HOPS_STR}},
    [MSTP_CIST_MAX_HOPS]            [2] = {{&array_validate_interval_lower_bound, MSTP_MAX_HOPS_INTERVAL_LOWER_BOUND_STR}},
    [MSTP_CIST_MAX_HOPS]            [3] = {{&array_validate_interval_upper_bound, MSTP_MAX_HOPS_INTERVAL_UPPER_BOUND_STR}},
    [MSTP_ID]                       [1] = {{&parse_dec_values_separated_with_spaces, ""}},
    [MSTP_ID]                       [2] = {{&array_delete_element, BASE_ZERO_STR}}, // 0 is used for CIST values
    [MSTP_BRIDGE_ID]                [1] = {{&find_and_get_next_word, BRIDGE_ID_STR}},
    [MSTP_SINCE_TOP_CHANGE]         [1] = {{&find_and_get_next_word, TIME_SINCE_TOPOLGY_CHANGED_STR}},
    [MSTP_TOP_CHANGES]              [1] = {{&find_and_get_next_word, TOPOLOGY_CHANGE_COUNT_STR}},
    [MSTP_DSGN_ROOT]                [1] = {{&get_first_word, ""}},
    [MSTP_ROOT_PATH_COST]           [1] = {{&find_and_get_next_word, INTERNAL_PATH_COST_STR}},
    [MSTP_ROOT_PORT]                [1] = {{&find_and_get_next_word, ROOT_PORT_STR}},
    [MSTP_BRIDGE_PRIORITY]          [1] = {{&find_and_get_next_word, BRIDGE_ID_STR}},
    [MSTP_BRIDGE_PRIORITY]          [2] = {{&array_drop_punctuation, ""}},
    [MSTP_BRIDGE_PRIORITY]          [3] = {{&array_shrink_string, BASE_ONE_STR}},
    [MSTP_BRIDGE_PRIORITY]          [4] = {{&array_convert_hex_string_to_long_int, ""}},
    [MSTP_CIST_PORT_DSGN_ROOT]      [1] = {{&get_first_word, ""}},
    [MSTP_CIST_PORT_TOP_CHANGE_ACK] [1] = {{&get_first_word, ""}},
    [MSTP_CIST_PORT_TOP_CHANGE_ACK] [2] = {{&validate_string_content, BASE_YES}},
    [MSTP_CIST_PORT_TOP_CHANGE_ACK] [3] = {{&validate_string_content, BASE_NO}},
    [MSTP_CIST_PORT_HELLO_TIME]     [1] = {{&get_first_word, ""}, {&validate_uint_32_number, ""}},
    [MSTP_CIST_PORT_HELLO_TIME]     [2] = {{&array_multiply_long_int_with, BASE_ONE_HUNDRED_STR}},
    [MSTP_CIST_PORT_OPER_EDGE_PORT] [1] = {{&get_first_word, ""}},
    [MSTP_CIST_PORT_OPER_EDGE_PORT] [2] = {{&validate_string_content, BASE_YES}},
    [MSTP_CIST_PORT_OPER_EDGE_PORT] [3] = {{&validate_string_content, BASE_NO}},
    [MSTP_CIST_PORT_PORT_ROLE]      [1] = {{&get_first_word, ""}},
    [MSTP_CIST_PORT_DISPUTED]       [1] = {{&get_first_word, ""}},
    [MSTP_CIST_PORT_DISPUTED]       [2] = {{&validate_string_content, BASE_YES}},
    [MSTP_CIST_PORT_DISPUTED]       [3] = {{&validate_string_content, BASE_NO}},
    [MSTP_CIST_PORT_REG_ROOT_ID]    [1] = {{&get_first_word, ""}},
    [MSTP_CIST_PORT_PATH_COST]      [1] = {{&get_first_word, ""}, {&validate_uint_32_number, ""}},
    [MSTP_CIST_PORT_ADMIN_PATH_COST][1] = {{&get_first_word, ""}, {&validate_uint_32_number, ""}},
    [MSTP_CIST_PORT_ADMIN_EDGE_PORT][1] = {{&get_first_word, ""}},
    [MSTP_CIST_PORT_ADMIN_EDGE_PORT][2] = {{&validate_string_content, BASE_YES}},
    [MSTP_CIST_PORT_ADMIN_EDGE_PORT][3] = {{&validate_string_content, BASE_NO}},
    [MSTP_CIST_PORT_MAC_ENABLED]    [1] = {{&get_first_word, ""}},
    [MSTP_CIST_PORT_MAC_ENABLED]    [2] = {{&validate_string_content, BASE_YES}},
    [MSTP_CIST_PORT_MAC_ENABLED]    [3] = {{&validate_string_content, BASE_NO}},
    [MSTP_CIST_PORT_RESTR_ROLE]     [1] = {{&get_first_word, ""}},
    [MSTP_CIST_PORT_RESTR_ROLE]     [2] = {{&validate_string_content, BASE_YES}},
    [MSTP_CIST_PORT_RESTR_ROLE]     [3] = {{&validate_string_content, BASE_NO}},
    [MSTP_CIST_PORT_RESTR_TCN]      [1] = {{&get_first_word, ""}},
    [MSTP_CIST_PORT_RESTR_TCN]      [2] = {{&validate_string_content, BASE_YES}},
    [MSTP_CIST_PORT_RESTR_TCN]      [3] = {{&validate_string_content, BASE_NO}},
    [MSTP_PORT_STATE]               [1] = {{&find_and_get_next_word, STATE_STR}},
    [MSTP_PORT_DSGN_ROOT]           [1] = {{&find_and_get_next_word, DSGN_REGIONAL_ROOT_STR}},
    [MSTP_PORT_DSGN_COST]           [1] = {{&find_and_get_next_word, DSGN_INTERNAL_ROOT_STR}},
    [MSTP_PORT_DSGN_BRIDGE]         [1] = {{&find_and_get_next_word, DSGN_BRIDGE_STR}},
    [MSTP_PORT_DSGN_PORT]           [1] = {{&find_and_get_next_word, DSGN_PORT_STR}},
    [MSTP_PORT_DSGN_PORT]           [2] = {{&array_take_value_after, POINT_STR}},
    [MSTP_PORT_DSGN_PORT]           [3] = {{&array_bitwise_AND_mask, X0F_MASK_STR}},
    [MSTP_PORT_ROLE]                [1] = {{&find_and_get_next_word, ROLE_STR}},
    [MSTP_PORT_ROLE]                [2] = {{&validate_string_content, BASE_ROOT_STR}},
    [MSTP_PORT_ROLE]                [3] = {{&validate_string_content, BASE_ALTERNATE_STR}},
    [MSTP_PORT_ROLE]                [4] = {{&validate_string_content, BASE_DESIGNATED_STR}},
    [MSTP_PORT_ROLE]                [5] = {{&validate_string_content, BASE_BACKUP_STR}},
    [MSTP_PORT_ROLE]                [6] = {{&validate_string_content, BASE_ROLE_DISABLED_STR}},
    [MSTP_PORT_DISPUTED]            [1] = {{&find_and_get_next_word, DISPUTED_STR}},
    [MSTP_PORT_DISPUTED]            [2] = {{&validate_string_content, BASE_YES}},
    [MSTP_PORT_DISPUTED]            [3] = {{&validate_string_content, BASE_NO}},
    [MSTP_PORT_PRIORITY]            [1] = {{&find_and_get_next_word, PORT_ID_STR}},
    [MSTP_PORT_PRIORITY]            [2] = {{&array_drop_punctuation, ""}},
    [MSTP_PORT_PRIORITY]            [3] = {{&array_shrink_string, BASE_ONE_STR}},
    [MSTP_PORT_PRIORITY]            [4] = {{&array_convert_hex_string_to_long_int, ""}},
    [MSTP_PORT_PATH_COST]           [1] = {{&find_and_get_next_word, INTERNAL_PORT_COST_STR}},
    [MSTP_CONF_ID_SELECTOR]         [1] = {{&find_and_get_next_word, FORMAT_SELECTOR_STR}},
    [MSTP_CONF_ID_CONF_NAME]        [1] = {{&find_and_get_next_word, CONFIGURATION_NAME_STR}, {&array_validate_string_length, BASE_THIRTY_TWO_STR}},
    [MSTP_CONF_ID_REVISION]         [1] = {{&find_and_get_next_word, REVISION_LEVEL_STR}},
    [MSTP_CONF_DIGEST]              [1] = {{&find_and_get_next_word, CONFIG_DIGEST_STR}},
    [MSTP_PORT_ADMIN_P2P]           [1] = {{&get_first_word, ""}},
    [MSTP_PORT_ADMIN_P2P]           [2] = {{&validate_string_content, BASE_YES}},
    [MSTP_PORT_ADMIN_P2P]           [3] = {{&validate_string_content, BASE_NO}},
    [MSTP_PORT_ADMIN_P2P]           [4] = {{&validate_string_content, BASE_AUTO}},
};

// Commands used for set system calls
char mstp_set_sys_call_commands[MSTP_MAX_OBJ_NUMBER][MAX_STR_LEN] = {
    [MSTP_MODULE]                    = "netopeer-manager rm --name %s",
    [MSTP_ENTRY_DEL]                 = "mstpctl deletetree %s %s",
    [MSTP_ENTRY_ADD]                 = "mstpctl createtree %s %s",
    [MSTP_DEL_FIDS]                  = "mstpctl setfid2mstid %s 0:%s",
    [MSTP_SET_FID_2_MSTID]           = "mstpctl setfid2mstid %s %s:%s",
    [MSTP_SET_VID_2_FID]             = "mstpctl setvid2fid %s %s:%s",
    [MSTP_BRIDGE_PRIORITY]           = "mstpctl settreeprio %s %s %s",
    [MSTP_CIST_MAX_HOPS]             = "mstpctl setmaxhops %s %s",
    [MSTP_CIST_PORT_ADMIN_PATH_COST] = "mstpctl setportpathcost %s %s %s",
    [MSTP_CIST_PORT_ADMIN_EDGE_PORT] = "mstpctl setportadminedge %s %s %s",
    [MSTP_CIST_PORT_MAC_ENABLED]     = "mstpctl setportp2p %s %s %s",
    [MSTP_CIST_PORT_RESTR_ROLE]      = "mstpctl setportrestrrole %s %s %s",
    [MSTP_CIST_PORT_RESTR_TCN]       = "mstpctl setportrestrtcn %s %s %s",
    [MSTP_PORT_PRIORITY]             = "mstpctl settreeportprio %s %s %s %s",
    [MSTP_PORT_PATH_COST]            = "mstpctl settreeportcost %s %s %s %s",
    [MSTP_CONF_ID_CONF_NAME]         = "mstpctl setmstconfid %s %s %s",
    [MSTP_CONF_ID_REVISION]          = "mstpctl setmstconfid %s %s %s",
    [MSTP_PORT_ADMIN_P2P]            = "mstpctl setportp2p %s %s %s",
};
