/*
 * TTTech libbase
 * Copyright(c) 2019 TTTech Industrial Automation AG.
 *
 * ALL RIGHTS RESERVED.
 * Usage of this software, including source code, netlists, documentation,
 * is subject to restrictions and conditions of the applicable license
 * agreement with TTTech Industrial Automation AG or its affiliates.
 *
 * All trademarks used are the property of their respective owners.
 *
 * TTTech Industrial Automation AG and its affiliates do not assume any liability
 * arising out of the application or use of any product described or shown
 * herein. TTTech Industrial Automation AG and its affiliates reserve the right to
 * make changes, at any time, in order to improve reliability, function or
 * design.
 *
 * Contact Information:
 * support@tttech-industrial.com
 * TTTech Industrial Automation AG, Schoenbrunnerstrasse 7, 1040 Vienna, Austria
 */

#include "base_private_defines.h"
#include "base_q_bridge_linux_tools.h"
#include "base_private_parsers.h"
#include "base_private_validators.h"
#include "base_private_combinators.h"

char q_bridge_map[Q_BRIDGE_MAX_OBJ_NUMBER][MAX_STR_LEN] = {
    // map between object index and object name for ietf-interfaces module
    [Q_BRIDGE_NAMES]                              = Q_BRIDGE_NAME_STR,
    [Q_BRIDGE_PORT_NAMES]                         = Q_BRIDGE_PORTS_STR,
    [Q_BRIDGE_ADDRESS]                            = Q_BRIDGE_ADDRESS_STR,
    [Q_BRIDGE_UPTIME]                             = Q_BRIDGE_UPTIME_STR,
    [Q_BRIDGE_PORT_NUMBER]                        = Q_BRIDGE_PORT_NUMBER_STR,
    [Q_BRIDGE_VIDS_BY_STATIC_FDB_ADDR]            = Q_BRIDGE_VIDS_BY_STATIC_FDB_ADDR_STR,
    [Q_BRIDGE_DEFAULT_VIDS_BY_STATIC_FDB_ADDR]    = Q_BRIDGE_DEFAULT_VIDS_BY_STATIC_FDB_ADDR_STR,
    [Q_BRIDGE_STATIC_ENTRIES]                     = Q_BRIDGE_STATIC_ENTRIES_STR,
    [Q_BRIDGE_DYNAMIC_ENTRIES]                    = Q_BRIDGE_DYNAMIC_ENTRIES_STR,
    [Q_BRIDGE_STATIC_VLAN_REG_ENTRY]              = Q_BRIDGE_STATIC_VLAN_REG_ENTRY_STR,
    [Q_BRIDGE_DYNAMIC_VLAN_REG_ENTRY]             = Q_BRIDGE_DYNAMIC_VLAN_REG_ENTRY_STR,
    [Q_BRIDGE_MAC_ADDR_REG_ENTRY]                 = Q_BRIDGE_MAC_ADDR_REG_ENTRY_STR,
    [Q_BRIDGE_COMP_DYN_ADDR]                      = Q_BRIDGE_COMP_DYN_ADDR_STR,
    [Q_BRIDGE_CONTROL_EL]                         = Q_BRIDGE_CONTROL_EL_STR,
    [Q_BRIDGE_CONNECT_ID]                         = Q_BRIDGE_CONNECT_ID_STR,
    [Q_BRIDGE_ADD_DEV_VID]                        = Q_BRIDGE_ADD_DEV_VID_STR,
    [Q_BRIDGE_DEL_DEV_VID]                        = Q_BRIDGE_DEL_DEV_VID_STR,
    [Q_BRIDGE_ADD_FDB_SELF_STATIC]                = Q_BRIDGE_ADD_FDB_SELF_STATIC_STR,
    [Q_BRIDGE_ADD_FDB_SELF_STATIC_VLAN]           = Q_BRIDGE_ADD_FDB_SELF_STATIC_VLAN_STR,
    [Q_BRIDGE_DEL_FDB_SELF_STATIC]                = Q_BRIDGE_DEL_FDB_SELF_STATIC_STR,
    [Q_BRIDGE_DEL_FDB_SELF_STATIC_VLAN]           = Q_BRIDGE_DEL_FDB_SELF_STATIC_VLAN_STR,
    [Q_BRIDGE_FIDS]                               = Q_BRIDGE_FIDS_STR,
    [Q_BRIDGE_MSTID_FID]                          = Q_BRIDGE_MSTID_FID_STR,
    [Q_BRIDGE_GET_BRIDGE_VLAN]                    = Q_BRIDGE_VLAN_STR,
    [Q_BIDGE_UNTAGGED_PORTS]                      = Q_BIDGE_UNTAGGED_PORTS_STR,
    [Q_BIDGE_EGRESS_PORTS]                        = Q_BIDGE_EGRESS_PORTS_STR,
    [Q_BRIDGE_STATIC_VLAN_TRANSMITTED]            = Q_BRIDGE_STATIC_VLAN_TRANSMITTED_STR,
    [Q_BRIDGE_STATIC_FDB_ADDRESSES]               = Q_BRIDGE_STATIC_FDB_ADDRESSES_STR,
    [Q_BRIDGE_FDB_PORT_NAMES]                     = Q_BRIDGE_FDB_PORT_NAMES_STR,
    [Q_BRIDGE_DEFAULT_FDB_PORT_NAMES]             = Q_BRIDGE_DEFAULT_FDB_PORT_NAMES_STR,
    [Q_BRIDGE_FDB_EXISTS]                         = Q_BRIDGE_FDB_EXISTS_STR,
    [Q_BRIDGE_NUM_OF_UNIQUE_FDB_ENTRIES]          = Q_BRIDGE_NUM_OF_UNIQUE_FDB_ENTRIES_STR,
    [Q_BRIDGE_COMP_DYNAMIC_VLAN_ADDR]             = Q_BRIDGE_COMP_DYNAMIC_VLAN_ADDR_STR,
    [Q_BRIDGE_MST]                                = Q_BRIDGE_MST_STR,
    [Q_BRIDGE_FID2VID_ALLOC]                      = Q_BRIDGE_FID2VID_ALLOC_STR,
    [Q_BRIDGE_VID]                                = Q_BRIDGE_VID_STR,
    [Q_BRIDGE_FID]                                = Q_BRIDGE_FID_STR,
    [Q_BRIDGE_PORT_PVID]                          = Q_BRIDGE_PORT_PVID_STR,
    [Q_BRIDGE_PORT_REF]                           = Q_BRIDGE_PORT_REF_STR,
    [Q_BRIDGE_PORT_NAME_BY_ID]                    = Q_BRIDGE_PORT_NAME_BY_ID_STR,
    [Q_BRIDGE_PORT_NAME_BY_VLAN]                  = Q_BRIDGE_PORT_NAME_BY_VLAN_STR,
    [Q_BRIDGE_PORT_VLANS_BY_NAME]                 = Q_BRIDGE_PORT_VLANS_BY_NAME_STR,
    [Q_BRIDGE_PORT_VLANS_WITHOUT_NAME]            = Q_BRIDGE_PORT_VLANS_WITHOUT_NAME_STR,
    [Q_BRIDGE_COMPRESSED_PORT_VLANS_BY_NAME]      = Q_BRIDGE_COMPRESSED_PORT_VLANS_BY_NAME_STR,
    [Q_BRIDGE_COMPRESSED_PORT_VLANS_WITHOUT_NAME] = Q_BRIDGE_COMPRESSED_PORT_VLANS_WITHOUT_NAME_STR,
};

// Commands used for get system calls
char q_bridge_get_sys_call_commands[Q_BRIDGE_MAX_OBJ_NUMBER][MAX_STR_LEN] = {
    [Q_BRIDGE_NAMES]                              = "ip -o link show type bridge",
    [Q_BRIDGE_PORT_NAMES]                         = "bridge -color=never link show",
    [Q_BRIDGE_ADDRESS]                            = "ip -o link show %s",
    [Q_BRIDGE_UPTIME]                             = "ps -p 1 -o etimes",
    [Q_BRIDGE_PORT_NUMBER]                        = "ip -o link show %s",
    [Q_BRIDGE_VIDS_BY_STATIC_FDB_ADDR]            = "bridge -color=never fdb",
    [Q_BRIDGE_DEFAULT_VIDS_BY_STATIC_FDB_ADDR]    = "bridge -color=never fdb",
    [Q_BRIDGE_STATIC_ENTRIES]                     = "bridge -color=never fdb show br %s",
    [Q_BRIDGE_DYNAMIC_ENTRIES]                    = "bridge -color=never fdb show br %s",
    [Q_BRIDGE_STATIC_VLAN_REG_ENTRY]              = "bridge -color=never fdb show br %s",
    [Q_BRIDGE_DYNAMIC_VLAN_REG_ENTRY]             = "bridge -color=never fdb show br %s",
    [Q_BRIDGE_MAC_ADDR_REG_ENTRY]                 = "bridge -color=never fdb show br %s",
    [Q_BRIDGE_COMP_DYN_ADDR]                      = "bridge -color=never fdb show br %s",
    [Q_BRIDGE_CONTROL_EL]                         = "ip -d link show %s",
    [Q_BRIDGE_CONNECT_ID]                         = "ip -o link show %s",
    [Q_BRIDGE_FIDS]                               = "mstpctl showfid2mstid %s",
    [Q_BRIDGE_MSTID_FID]                          = "mstpctl showfid2mstid %s",
    [Q_BRIDGE_GET_BRIDGE_VLAN]                    = "bridge -color=never fdb show br %s",
    [Q_BIDGE_UNTAGGED_PORTS]                      = "bridge -color=never vlan show dev %s",
    [Q_BIDGE_EGRESS_PORTS]                        = "bridge -color=never vlan show dev %s",
    [Q_BRIDGE_STATIC_VLAN_TRANSMITTED]            = "bridge -color=never -compressvlans vlan show dev %s",
    [Q_BRIDGE_STATIC_FDB_ADDRESSES]               = "bridge -color=never fdb",
    [Q_BRIDGE_FDB_PORT_NAMES]                     = "bridge -color=never fdb",
    [Q_BRIDGE_DEFAULT_FDB_PORT_NAMES]             = "bridge -color=never fdb",
    [Q_BRIDGE_FDB_EXISTS]                         = "bridge -color=never fdb",
    [Q_BRIDGE_NUM_OF_UNIQUE_FDB_ENTRIES]          = "bridge -color=never fdb show br %s state static",
    [Q_BRIDGE_COMP_DYNAMIC_VLAN_ADDR]             = "bridge -color=never fdb show br %s",
    [Q_BRIDGE_MST]                                = "mstpctl showvid2fid %s",
    [Q_BRIDGE_FID2VID_ALLOC]                      = "mstpctl showvid2fid %s",
    [Q_BRIDGE_VID]                                = "mstpctl showvid2fid %s",
    [Q_BRIDGE_FID]                                = "mstpctl showvid2fid %s",
    [Q_BRIDGE_PORT_PVID]                          = "bridge -color=never vlan show dev %s",
    [Q_BRIDGE_PORT_REF]                           = "ip -o link show %s",
    [Q_BRIDGE_PORT_NAME_BY_ID]                    = "bridge -color=never -o link show",
    [Q_BRIDGE_PORT_NAME_BY_VLAN]                  = "bridge -color=never -compressvlans vlan show vid %s",
    [Q_BRIDGE_PORT_VLANS_BY_NAME]                 = "bridge -color=never vlan show dev %s",
    [Q_BRIDGE_PORT_VLANS_WITHOUT_NAME]            = "bridge -color=never vlan show dev %s",
    [Q_BRIDGE_COMPRESSED_PORT_VLANS_BY_NAME]      = "bridge -color=never -compressvlans vlan show dev %s",
    [Q_BRIDGE_COMPRESSED_PORT_VLANS_WITHOUT_NAME] = "bridge -color=never -compressvlans vlan show dev %s",
};

syscall_fn_t q_bridge_syscalls[Q_BRIDGE_MAX_OBJ_NUMBER] = {
    [Q_BRIDGE_NAMES]                              = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_PORT_NAMES]                         = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_ADDRESS]                            = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_UPTIME]                             = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_PORT_NUMBER]                        = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_VIDS_BY_STATIC_FDB_ADDR]            = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_DEFAULT_VIDS_BY_STATIC_FDB_ADDR]    = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_STATIC_ENTRIES]                     = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_DYNAMIC_ENTRIES]                    = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_STATIC_VLAN_REG_ENTRY]              = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_DYNAMIC_VLAN_REG_ENTRY]             = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_MAC_ADDR_REG_ENTRY]                 = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_COMP_DYN_ADDR]                      = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_CONTROL_EL]                         = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_CONNECT_ID]                         = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_FIDS]                               = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_MSTID_FID]                          = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_GET_BRIDGE_VLAN]                    = (syscall_fn_t)&get_str_sys_call,
    [Q_BIDGE_UNTAGGED_PORTS]                      = (syscall_fn_t)&get_str_sys_call,
    [Q_BIDGE_EGRESS_PORTS]                        = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_STATIC_VLAN_TRANSMITTED]            = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_STATIC_FDB_ADDRESSES]               = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_DEFAULT_FDB_PORT_NAMES]             = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_FDB_EXISTS]                         = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_NUM_OF_UNIQUE_FDB_ENTRIES]          = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_FDB_PORT_NAMES]                     = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_COMP_DYNAMIC_VLAN_ADDR]             = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_MST]                                = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_FID2VID_ALLOC]                      = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_VID]                                = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_FID]                                = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_PORT_PVID]                          = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_PORT_REF]                           = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_PORT_NAME_BY_ID]                    = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_PORT_NAME_BY_VLAN]                  = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_PORT_VLANS_BY_NAME]                 = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_PORT_VLANS_WITHOUT_NAME]            = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_COMPRESSED_PORT_VLANS_BY_NAME]      = (syscall_fn_t)&get_str_sys_call,
    [Q_BRIDGE_COMPRESSED_PORT_VLANS_WITHOUT_NAME] = (syscall_fn_t)&get_str_sys_call,
};

// Number of combinators per system call (object index)
int q_bridge_num_of_combinators[Q_BRIDGE_MAX_OBJ_NUMBER] = {
    [Q_BRIDGE_NAMES]                              = 4,
    [Q_BRIDGE_PORT_NAMES]                         = 4,
    [Q_BRIDGE_ADDRESS]                            = 2,
    [Q_BRIDGE_UPTIME]                             = 2,
    [Q_BRIDGE_PORT_NUMBER]                        = 3,
    [Q_BRIDGE_VIDS_BY_STATIC_FDB_ADDR]            = 3,
    [Q_BRIDGE_DEFAULT_VIDS_BY_STATIC_FDB_ADDR]    = 3,
    [Q_BRIDGE_STATIC_ENTRIES]                     = 2,
    [Q_BRIDGE_DYNAMIC_ENTRIES]                    = 2,
    [Q_BRIDGE_STATIC_VLAN_REG_ENTRY]              = 2,
    [Q_BRIDGE_DYNAMIC_VLAN_REG_ENTRY]             = 2,
    [Q_BRIDGE_MAC_ADDR_REG_ENTRY]                 = 4,
    [Q_BRIDGE_COMP_DYN_ADDR]                      = 2,
    [Q_BRIDGE_CONTROL_EL]                         = 2,
    [Q_BRIDGE_CONNECT_ID]                         = 3,
    [Q_BRIDGE_FIDS]                               = 2,
    [Q_BRIDGE_MSTID_FID]                          = 2,
    [Q_BRIDGE_GET_BRIDGE_VLAN]                    = 3,
    [Q_BIDGE_UNTAGGED_PORTS]                      = 2,
    [Q_BIDGE_EGRESS_PORTS]                        = 2,
    [Q_BRIDGE_STATIC_VLAN_TRANSMITTED]            = 2,
    [Q_BRIDGE_STATIC_FDB_ADDRESSES]               = 3,
    [Q_BRIDGE_FDB_PORT_NAMES]                     = 3,
    [Q_BRIDGE_DEFAULT_FDB_PORT_NAMES]             = 3,
    [Q_BRIDGE_FDB_EXISTS]                         = 2,
    [Q_BRIDGE_NUM_OF_UNIQUE_FDB_ENTRIES]          = 3,
    [Q_BRIDGE_COMP_DYNAMIC_VLAN_ADDR]             = 2,
    [Q_BRIDGE_MST]                                = 2,
    [Q_BRIDGE_FID2VID_ALLOC]                      = 3,
    [Q_BRIDGE_VID]                                = 2,
    [Q_BRIDGE_FID]                                = 3,
    [Q_BRIDGE_PORT_PVID]                          = 4,
    [Q_BRIDGE_PORT_REF]                           = 3,
    [Q_BRIDGE_PORT_NAME_BY_ID]                    = 4,
    [Q_BRIDGE_PORT_NAME_BY_VLAN]                  = 3,
    [Q_BRIDGE_PORT_VLANS_BY_NAME]                 = 3,
    [Q_BRIDGE_PORT_VLANS_WITHOUT_NAME]            = 3,
    [Q_BRIDGE_COMPRESSED_PORT_VLANS_BY_NAME]      = 3,
    [Q_BRIDGE_COMPRESSED_PORT_VLANS_WITHOUT_NAME] = 3,
};

combinator_fn_t q_bridge_combinators[Q_BRIDGE_MAX_OBJ_NUMBER][MAX_COMBINATORS_NUM] = {
    [Q_BRIDGE_NAMES]                              = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator},
    [Q_BRIDGE_PORT_NAMES]                         = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator},
    [Q_BRIDGE_ADDRESS]                            = {&combinator_comb, &repeat_until_null_with_check},
    [Q_BRIDGE_UPTIME]                             = {&combinator_comb, &repeat_check_and_get_next_line},
    [Q_BRIDGE_PORT_NUMBER]                        = {&combinator_comb, &repeat_until_null_with_check, &no_combinator},
    [Q_BRIDGE_VIDS_BY_STATIC_FDB_ADDR]            = {&combinator_comb, &repeat_until_null_with_check, &no_combinator},
    [Q_BRIDGE_DEFAULT_VIDS_BY_STATIC_FDB_ADDR]    = {&combinator_comb, &AND_combinator, &no_combinator},
    [Q_BRIDGE_STATIC_ENTRIES]                     = {&combinator_comb, &repeat_until_eof_and_count},
    [Q_BRIDGE_DYNAMIC_ENTRIES]                    = {&combinator_comb, &repeat_until_eof_and_count},
    [Q_BRIDGE_STATIC_VLAN_REG_ENTRY]              = {&combinator_comb, &repeat_until_eof_and_count},
    [Q_BRIDGE_DYNAMIC_VLAN_REG_ENTRY]             = {&combinator_comb, &repeat_until_eof_and_count},
    [Q_BRIDGE_MAC_ADDR_REG_ENTRY]                 = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator},
    [Q_BRIDGE_COMP_DYN_ADDR]                      = {&combinator_comb, &repeat_until_null_with_check},
    [Q_BRIDGE_CONTROL_EL]                         = {&combinator_comb, &repeat_until_null_with_check},
    [Q_BRIDGE_CONNECT_ID]                         = {&combinator_comb, &repeat_until_null_with_check, &no_combinator},
    [Q_BRIDGE_FIDS]                               = {&combinator_comb, &repeat_until_null_with_check},
    [Q_BRIDGE_MSTID_FID]                          = {&combinator_comb, &repeat_until_null_with_check},
    [Q_BRIDGE_GET_BRIDGE_VLAN]                    = {&combinator_comb, &repeat_until_null_with_check, &no_combinator},
    [Q_BIDGE_UNTAGGED_PORTS]                      = {&combinator_comb, &AND_combinator},
    [Q_BIDGE_EGRESS_PORTS]                        = {&combinator_comb, &repeat_until_null_with_check},
    [Q_BRIDGE_STATIC_VLAN_TRANSMITTED]            = {&combinator_comb, &AND_combinator},
    [Q_BRIDGE_STATIC_FDB_ADDRESSES]               = {&combinator_comb, &repeat_until_null_with_check, &no_combinator},
    [Q_BRIDGE_FDB_PORT_NAMES]                     = {&combinator_comb, &repeat_until_null_with_check, &no_combinator},
    [Q_BRIDGE_DEFAULT_FDB_PORT_NAMES]             = {&combinator_comb, &repeat_until_null_with_check, &no_combinator},
    [Q_BRIDGE_FDB_EXISTS]                         = {&combinator_comb, &AND_combinator},
    [Q_BRIDGE_NUM_OF_UNIQUE_FDB_ENTRIES]          = {&combinator_comb, &repeat_until_null_with_check, &no_combinator},
    [Q_BRIDGE_COMP_DYNAMIC_VLAN_ADDR]             = {&combinator_comb, &repeat_until_null_with_check},
    [Q_BRIDGE_MST]                                = {&combinator_comb, &repeat_until_null_with_check},
    [Q_BRIDGE_FID2VID_ALLOC]                      = {&combinator_comb, &repeat_until_null_with_check, &no_combinator},
    [Q_BRIDGE_VID]                                = {&combinator_comb, &repeat_until_null_with_check},
    [Q_BRIDGE_FID]                                = {&combinator_comb, &repeat_until_null_with_check, &no_combinator},
    [Q_BRIDGE_PORT_PVID]                          = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator},
    [Q_BRIDGE_PORT_REF]                           = {&combinator_comb, &repeat_until_null_with_check, &no_combinator},
    [Q_BRIDGE_PORT_NAME_BY_ID]                    = {&combinator_comb, &repeat_until_null_with_check, &no_combinator, &no_combinator},
    [Q_BRIDGE_PORT_NAME_BY_VLAN]                  = {&combinator_comb, &repeat_until_null_with_check, &no_combinator},
    [Q_BRIDGE_PORT_VLANS_BY_NAME]                 = {&combinator_comb, &repeat_until_null_with_check, &no_combinator},
    [Q_BRIDGE_PORT_VLANS_WITHOUT_NAME]            = {&combinator_comb, &repeat_until_null_with_check, &no_combinator},
    [Q_BRIDGE_COMPRESSED_PORT_VLANS_BY_NAME]      = {&combinator_comb, &repeat_until_null_with_check, &no_combinator},
    [Q_BRIDGE_COMPRESSED_PORT_VLANS_WITHOUT_NAME] = {&combinator_comb, &repeat_until_null_with_check, &no_combinator},
};

// We need a number of callbacks per combinator if we are using more than one
int q_bridge_num_of_cb[Q_BRIDGE_MAX_OBJ_NUMBER][MAX_COMBINATORS_NUM] = {
    // A combinator uses a predefined amount of callbacks, actually set here
    [Q_BRIDGE_NAMES]                              = {0, 2, 1, 1},
    [Q_BRIDGE_PORT_NAMES]                         = {0, 1, 1, 1},
    [Q_BRIDGE_ADDRESS]                            = {0, 1},
    [Q_BRIDGE_UPTIME]                             = {0, 2},
    [Q_BRIDGE_PORT_NUMBER]                        = {0, 1, 1},
    [Q_BRIDGE_VIDS_BY_STATIC_FDB_ADDR]            = {0, 3, 1},
    [Q_BRIDGE_DEFAULT_VIDS_BY_STATIC_FDB_ADDR]    = {0, 3, 1},
    [Q_BRIDGE_STATIC_ENTRIES]                     = {0, 1},
    [Q_BRIDGE_DYNAMIC_ENTRIES]                    = {0, 1},
    [Q_BRIDGE_STATIC_VLAN_REG_ENTRY]              = {0, 2},
    [Q_BRIDGE_DYNAMIC_VLAN_REG_ENTRY]             = {0, 2},
    [Q_BRIDGE_MAC_ADDR_REG_ENTRY]                 = {0, 1, 1, 1},
    [Q_BRIDGE_COMP_DYN_ADDR]                      = {0, 3},
    [Q_BRIDGE_CONTROL_EL]                         = {0, 3},
    [Q_BRIDGE_CONNECT_ID]                         = {0, 1, 1},
    [Q_BRIDGE_FIDS]                               = {0, 1},
    [Q_BRIDGE_MSTID_FID]                          = {0, 1},
    [Q_BRIDGE_GET_BRIDGE_VLAN]                    = {0, 1, 1},
    [Q_BIDGE_UNTAGGED_PORTS]                      = {0, 2},
    [Q_BIDGE_EGRESS_PORTS]                        = {0, 1},
    [Q_BRIDGE_STATIC_VLAN_TRANSMITTED]            = {0, 2},
    [Q_BRIDGE_STATIC_FDB_ADDRESSES]               = {0, 2, 1},
    [Q_BRIDGE_FDB_PORT_NAMES]                     = {0, 4, 1},
    [Q_BRIDGE_DEFAULT_FDB_PORT_NAMES]             = {0, 4, 1},
    [Q_BRIDGE_FDB_EXISTS]                         = {0, 3},
    [Q_BRIDGE_NUM_OF_UNIQUE_FDB_ENTRIES]          = {0, 1, 1},
    [Q_BRIDGE_COMP_DYNAMIC_VLAN_ADDR]             = {0, 3},
    [Q_BRIDGE_MST]                                = {0, 2},
    [Q_BRIDGE_FID2VID_ALLOC]                      = {0, 1, 1},
    [Q_BRIDGE_VID]                                = {0, 1},
    [Q_BRIDGE_FID]                                = {0, 2, 1},
    [Q_BRIDGE_PORT_PVID]                          = {0, 1, 1, 1},
    [Q_BRIDGE_PORT_REF]                           = {0, 1, 1},
    [Q_BRIDGE_PORT_NAME_BY_ID]                    = {0, 1, 1, 1},
    [Q_BRIDGE_PORT_NAME_BY_VLAN]                  = {0, 3, 1},
    [Q_BRIDGE_PORT_VLANS_BY_NAME]                 = {0, 1, 1},
    [Q_BRIDGE_PORT_VLANS_WITHOUT_NAME]            = {0, 3, 1},
    [Q_BRIDGE_COMPRESSED_PORT_VLANS_BY_NAME]      = {0, 1, 1},
    [Q_BRIDGE_COMPRESSED_PORT_VLANS_WITHOUT_NAME] = {0, 3, 1},
};

// read it like: at object index, at combinator index
parser_spec_t q_bridge_parsing_cb[Q_BRIDGE_MAX_OBJ_NUMBER][MAX_COMBINATORS_NUM][MAX_CALLBACKS_NUM] = {
    [Q_BRIDGE_NAMES][1]                              = {{&find_on_line, LESS_THAN_STR}, {&find_and_get_next_word, COLON_AND_SPACE_STR}},
    [Q_BRIDGE_NAMES][2]                              = {{&array_until_match_case, COLON_STR}},
    [Q_BRIDGE_NAMES][3]                              = {{&array_uniq_elements, ""}},
    [Q_BRIDGE_PORT_NAMES][1]                         = {{&find_and_get_next_word, COLON_STR}},
    [Q_BRIDGE_PORT_NAMES][2]                         = {{&array_drop_punctuation, ""}},
    [Q_BRIDGE_PORT_NAMES][3]                         = {{&array_uniq_elements, ""}},
    [Q_BRIDGE_ADDRESS][1]                            = {{&find_and_get_next_word, BASE_LINK_ETHER}},
    [Q_BRIDGE_UPTIME][1]                             = {{&find_on_line, UPTIME_ELAPSED}, {get_first_word, ""}},
    [Q_BRIDGE_PORT_NUMBER][1]                        = {{&get_first_word, ""}},
    [Q_BRIDGE_PORT_NUMBER][2]                        = {{&array_drop_punctuation, ""}},
    [Q_BRIDGE_VIDS_BY_STATIC_FDB_ADDR][1]            = {{&find_on_line, ""}, {&find_on_line, Q_BRIDGE_STATIC}, {&find_and_get_next_word, Q_BRIDGE_COMP_VLAN}},
    [Q_BRIDGE_VIDS_BY_STATIC_FDB_ADDR][2]            = {{&array_uniq_elements, ""}},
    [Q_BRIDGE_DEFAULT_VIDS_BY_STATIC_FDB_ADDR][1]    = {{&find_on_line, ""}, {&find_on_line, Q_BRIDGE_STATIC}, {&is_not_on_line, Q_BRIDGE_COMP_VLAN}},
    [Q_BRIDGE_DEFAULT_VIDS_BY_STATIC_FDB_ADDR][2]    = {{&array_uniq_elements, ""}},
    [Q_BRIDGE_STATIC_ENTRIES][1]                     = {{&find_on_line, Q_BRIDGE_STATIC}},
    [Q_BRIDGE_DYNAMIC_ENTRIES][1]                    = {{&find_on_line, Q_BRIDGE_DYNAMIC}},
    [Q_BRIDGE_STATIC_VLAN_REG_ENTRY][1]              = {{&find_on_line, Q_BRIDGE_STATIC}, {&find_on_line, Q_BRIDGE_COMP_VLAN}},
    [Q_BRIDGE_DYNAMIC_VLAN_REG_ENTRY][1]             = {{&find_on_line, Q_BRIDGE_DYNAMIC}, {&find_on_line, Q_BRIDGE_COMP_VLAN}},
    [Q_BRIDGE_MAC_ADDR_REG_ENTRY][1]                 = {{&get_first_word, ""}},
    [Q_BRIDGE_MAC_ADDR_REG_ENTRY][2]                 = {{&array_uniq_elements, ""}},
    [Q_BRIDGE_MAC_ADDR_REG_ENTRY][3]                 = {{&array_count_elements, ""}},
    [Q_BRIDGE_COMP_DYN_ADDR][1]                      = {{&find_on_line, Q_BRIDGE_DYNAMIC}, {&find_on_line, Q_BRIDGE_COMP_VLAN}, {&get_first_word, ""}},
    [Q_BRIDGE_CONTROL_EL][1]                         = {{&find_on_line, STATE_STR}, {&find_on_line, PRIORITY_STR}, {&find_and_get_next_word, STATE_STR}},
    [Q_BRIDGE_CONNECT_ID][1]                         = {{&get_first_word, ""}},
    [Q_BRIDGE_CONNECT_ID][2]                         = {{&array_drop_punctuation, ""}},
    [Q_BRIDGE_FIDS][1]                               = {{&find_and_get_next_word, ""}},
    [Q_BRIDGE_MSTID_FID][1]                          = {{&find_and_get_next_word, ""}},
    [Q_BRIDGE_GET_BRIDGE_VLAN][1]                    = {{&find_and_get_next_word, Q_BRIDGE_COMP_VLAN}},
    [Q_BRIDGE_GET_BRIDGE_VLAN][2]                    = {{&array_uniq_elements, ""}},
    [Q_BIDGE_UNTAGGED_PORTS][1]                      = {{&find_on_line, ""}, {&find_on_line, Q_BRIDGE_VLAN_UNTAGGED}},
    [Q_BIDGE_EGRESS_PORTS][1]                        = {{&find_on_line, ""}},
    [Q_BRIDGE_STATIC_VLAN_TRANSMITTED][1]            = {{&find_on_line, ""}, {&find_on_line_and_fill_result_array, Q_BRIDGE_VLAN_UNTAGGED}},
    [Q_BRIDGE_STATIC_FDB_ADDRESSES][1]               = {{&find_on_line, Q_BRIDGE_STATIC}, {&get_first_word, ""}},
    [Q_BRIDGE_STATIC_FDB_ADDRESSES][2]               = {{&array_uniq_elements, ""}},
    [Q_BRIDGE_FDB_PORT_NAMES][1]                     = {{&find_on_line, ""}, {&find_on_line, ""}, {&find_on_line, Q_BRIDGE_STATIC}, {&find_and_get_next_word, BASE_DEV_STR}},
    [Q_BRIDGE_FDB_PORT_NAMES][2]                     = {{&array_uniq_elements, ""}},
    [Q_BRIDGE_DEFAULT_FDB_PORT_NAMES][1]             = {{&find_on_line, ""}, {&find_on_line, Q_BRIDGE_STATIC}, {&is_not_on_line, Q_BRIDGE_COMP_VLAN}, {&find_and_get_next_word, BASE_DEV_STR}},
    [Q_BRIDGE_DEFAULT_FDB_PORT_NAMES][2]             = {{&array_uniq_elements, ""}},
    [Q_BRIDGE_FDB_EXISTS][1]                         = {{&find_on_line, Q_BRIDGE_STATIC}, {&find_on_line, ""}, {&find_on_line, ""}},
    [Q_BRIDGE_NUM_OF_UNIQUE_FDB_ENTRIES][1]          = {{&get_all_lines, ""}},
    [Q_BRIDGE_NUM_OF_UNIQUE_FDB_ENTRIES][2]          = {{&array_count_elements, ""}},
    [Q_BRIDGE_COMP_DYNAMIC_VLAN_ADDR][1]             = {{&find_on_line, Q_BRIDGE_DYNAMIC}, {&find_on_line, ""}, {&find_and_get_next_word, Q_BRIDGE_COMP_VLAN}},
    [Q_BRIDGE_MST][1]                                = {{&find_on_line, Q_BRIDGE_VALUE_FID_STR}, {&find_and_get_next_word, COLON_STR}},
    [Q_BRIDGE_FID2VID_ALLOC][1]                      = {{&find_and_get_next_word, Q_BRIDGE_VALUE_FID_STR}},
    [Q_BRIDGE_FID2VID_ALLOC][2]                      = {{&array_until_match_case, COLON_STR}},
    [Q_BRIDGE_VID][1]                                = {{&find_and_get_next_word, ""}},
    [Q_BRIDGE_FID][1]                                = {{&find_on_line, ""}, {&find_and_get_next_word, Q_BRIDGE_VALUE_FID_STR}},
    [Q_BRIDGE_FID][2]                                = {{&array_until_match_case, COLON_STR}},
    [Q_BRIDGE_PORT_PVID][1]                          = {{&find_and_get_previous_word, Q_BRIDGE_VALUE_PVID_STR}},
    [Q_BRIDGE_PORT_PVID][2]                          = {{&array_uniq_elements, ""}},
    [Q_BRIDGE_PORT_PVID][3]                          = {{&validate_uint_32_number, ""}},
    [Q_BRIDGE_PORT_REF][1]                           = {{&get_first_word, ""}},
    [Q_BRIDGE_PORT_REF][2]                           = {{&array_drop_punctuation, ""}},
    [Q_BRIDGE_PORT_NAME_BY_ID][1]                    = {{&find_and_get_next_word, ""}},
    [Q_BRIDGE_PORT_NAME_BY_ID][2]                    = {{&array_drop_punctuation, ""}},
    [Q_BRIDGE_PORT_NAME_BY_ID][3]                    = {{&array_uniq_elements, ""}},
    [Q_BRIDGE_PORT_NAME_BY_VLAN][1]                  = {{&find_on_line, ""}, {&is_not_on_line, ""}, {&get_first_word, ""}},
    [Q_BRIDGE_PORT_NAME_BY_VLAN][2]                  = {{&array_uniq_elements, ""}},
    [Q_BRIDGE_PORT_VLANS_BY_NAME][1]                 = {{&find_and_get_next_word, ""}},
    [Q_BRIDGE_PORT_VLANS_BY_NAME][2]                 = {{&array_uniq_elements, ""}},
    [Q_BRIDGE_PORT_VLANS_WITHOUT_NAME][1]            = {{&is_not_on_line, ""}, {&is_not_on_line, BASE_PORT_STR}, {&get_first_word, ""}},
    [Q_BRIDGE_PORT_VLANS_WITHOUT_NAME][2]            = {{&array_uniq_elements, ""}},
    [Q_BRIDGE_COMPRESSED_PORT_VLANS_BY_NAME][1]      = {{&find_and_get_next_word, ""}},
    [Q_BRIDGE_COMPRESSED_PORT_VLANS_BY_NAME][2]      = {{&array_uniq_elements, ""}},
    [Q_BRIDGE_COMPRESSED_PORT_VLANS_WITHOUT_NAME][1] = {{&is_not_on_line, ""}, {&is_not_on_line, BASE_PORT_STR}, {&get_first_word, ""}},
    [Q_BRIDGE_COMPRESSED_PORT_VLANS_WITHOUT_NAME][2] = {{&array_uniq_elements, ""}},
};

// Commands used for set system calls
char q_bridge_set_sys_call_commands[Q_BRIDGE_MAX_OBJ_NUMBER][MAX_STR_LEN] = {
    [Q_BRIDGE_ADD_DEV_VID]              = "bridge -compressvlans vlan add dev %s vid %s %s",
    [Q_BRIDGE_DEL_DEV_VID]              = "bridge -compressvlans vlan del dev %s vid %s %s",
    [Q_BRIDGE_ADD_FDB_SELF_STATIC]      = "bridge fdb add %s dev %s self static",
    [Q_BRIDGE_ADD_FDB_SELF_STATIC_VLAN] = "bridge fdb add %s dev %s self static vlan %s",
    [Q_BRIDGE_DEL_FDB_SELF_STATIC]      = "bridge fdb del %s dev %s self static",
    [Q_BRIDGE_DEL_FDB_SELF_STATIC_VLAN] = "bridge fdb del %s dev %s self static vlan %s",
    [Q_BRIDGE_PORT_PVID]                = "bridge vlan add vid %s dev %s pvid untagged",
};
